<a href="#header-nav" class="skip-link skip-nav">
	<span class="icon ic ic-menu"></span>
	<span class="label"><?php echo __('Menú') ?></span>
</a>
<a href="#header-search" class="skip-link skip-search">
	<span class="icon ic ic-search"></span>
	<span class="label"><?php echo __('Búsqueda') ?></span>
</a>
<a href="#header-account" class="skip-link skip-account">
	<span class="icon ic ic-user"></span>
	<span class="label"><?php echo __('Mi cuenta') ?></span>
</a>