<style>
    button#paises {
	display: block;
    float: right;
    font-weight: normal;
    font-size: 12px;
    border: 1px solid #ccc;
    padding: 10px;
    background: url(<?php echo $this->getViewFileUrl("images/banderas/mexico.png");?>) 7px 6px no-repeat #ffffff;
    line-height: 1.2;
    color: #3b3b3b !important;
    border-radius: 0;
    width: 205px;
    text-align: right;
    margin-top: 1px;
}

.btn-pais.dropdown-toggle::after {
    display: inline-block;
    margin-left: 30px;
    vertical-align: .1em;
    content: "";
    border-top: .5em solid;
    border-right: .5em solid transparent;
    border-bottom: 0;
    border-left: .5em solid transparent;
}

.btn-pais:focus{
	box-shadow:none;
}

.selec-pais{
	background: #fff;
    width: 236px;
    box-shadow: 0 5px 5px rgba(0, 0, 0, 0.15);
    border-top: 1px solid #ccc;
    border-radius: 0;
    padding: 0;
        margin-top: 37px;
    z-index: 999;
    position: absolute;
	right: 0;
}

.selec-pais ul {
    list-style: none;
    padding: 0;
    *overflow: hidden;
    margin: 0;
}

.banderas-header .arrow-down{
    display: inline-block;
    height: 0;
    width: 0;
    border-top: 6px solid #3b3b3b;
    border-right: 6px solid transparent;
    border-left: 6px solid transparent;
    margin-left: 30px;
}

.selec-pais ul li {
    width: 100%;
    float: left;
    border-bottom: 1px solid #ccc;
	margin: 0;
    padding: 10px;
	text-align: left;
}

.selec-pais ul li:hover {
    background: #65ABD9;
}

.selec-pais li a {
    padding: 0px 4px 1px 46px;
    font-size: 12px;
    text-transform: uppercase;
    color: #777;
    background-position: 10px center !important;
    text-align: left;
    height: 40px;
}

.selec-pais li a:hover{
	text-decoration: none;
}

.selec-pais li a span {
    font-weight: 100;
    text-transform: lowercase;
    color: #777;
}

.banderas-header {
    position: absolute;
    top: 0px;
    right: 51%;
}

      </style>
	 
 <div class="banderas-header" data-block="country">
  <!--<button class="btn btn-pais dropdown-toggle" type="button" id="paises" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
  <button class="btn btn-pais action showpais" type="button" id="paises" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Selecciona tu país
	<span class="arrow-down"></span>
  </button>
  <!--<div class="dropdown-menu selec-pais dropdown-menu-right" aria-labelledby="paises"> block block-minicart-->
  <div class="selec-pais "
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=country]",
                "triggerTarget":".showpais",
                "timeout": "2000",
                "closeOnMouseLeave": true,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
    <ul>
      <li><a href="https://www.thehouseofmarley.com/" target="_blank" style="background:url(<?php echo $this->getViewFileUrl("images/banderas/usa.png");?>) no-repeat;">USA <span> English</span></a></li>
      <li><a href="https://www.thehouseofmarley.com.ar" target="_blank" style="background:url(<?php echo $this->getViewFileUrl("images/banderas/argentina.png");?>) no-repeat;"> Argentina <span> Español</span></a></li>
      <li><a href="https://www.thehouseofmarley.co.uk/" target="_blank" style="background:url(<?php echo $this->getViewFileUrl("images/banderas/uk.png");?>) no-repeat;">United Kingdom <span> English</span></a></li>
      <li><a href="https://marley.nl/" target="_blank" style="background:url(<?php echo $this->getViewFileUrl("images/banderas/holanda.png");?>) no-repeat;">Holanda <span> Nederlands</span></a></li>
      <li><a href="https://www.thehouseofmarley.it" target="_blank" style="background:url(<?php echo $this->getViewFileUrl("images/banderas/italy.png");?>) no-repeat;">Italia <span> Italiano</span></a></li>
      <li><a href="https://www.thehouseofmarley.com.au" target="_blank" style="background:url(<?php echo $this->getViewFileUrl("images/banderas/australia.png");?>) no-repeat;">Autralia <span> English</span></a></li>
      <li><a href="https://www.thehouseofmarley.com.au" target="_blank" style="background:url(<?php echo $this->getViewFileUrl("images/banderas/japon.png");?>) no-repeat;">Japon <span> Japones</span></a></li>
      <li><a href="https://houseofmarley.co.il/" target="_blank" style="background:url(<?php echo $this->getViewFileUrl("images/banderas/israel.png");?>) no-repeat;">Israel<span> Hebreo</span></a></li>
      <li><a href="http://www.thehouseofmarley.cl" target="_blank" style="background:url(<?php echo $this->getViewFileUrl("images/banderas/chile.png");?>) no-repeat;">Chile<span> español</span></a></li>
      <li><a href="#" target="_blank" style="background:url(<?php echo $this->getViewFileUrl("images/banderas/mexico.png");?>) no-repeat;">México<span> español</span></a></li>
    </ul>
  </div>
  </div>