<?php
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$facebook = $_helperCdi->getStoreConfig('general/store_information/facebook_link');
$instagram = $_helperCdi->getStoreConfig('general/store_information/instagram_link');
$youtube = $_helperCdi->getStoreConfig('general/store_information/youtube_link');
$twitter = $_helperCdi->getStoreConfig('general/store_information/twitter_link');
$spotify = $_helperCdi->getStoreConfig('general/store_information/spotify_link');
$pinterest = $_helperCdi->getStoreConfig('general/store_information/pinterest_link');
$terms = $_helperCdi->getStoreConfig('general/store_information/termsofuse');
$privacy = $_helperCdi->getStoreConfig('general/store_information/privacypolicy');
?>
<div class="footer">
    <div class="container">
		<div class="footer-top row">
			<div class="col-sm-3 col-12 footer-social">
				<!--<h4><?php echo __('SOL REPUBLIC')?></h4>-->
				<img class="footerTitle" src="<?php echo $this->getViewFileUrl("images/logos/SOL-footer-logo.jpg");?>" alt="SOL REPUBLIC" title="SOL REPUBLIC" _secure="true">
				<div class="row">
					<?php if($facebook){ ?>
						<div class="col-md-4 col-xs-4">
							<a href="<?php echo $facebook?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-facebook.png");?>" alt="Facebook" title="Facebook" _secure="true"></a>
						</div>
					<?php } ?>
					<?php if($instagram){ ?>
					<div class="col-md-4 col-xs-4">
						<a href="<?php echo $instagram?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-instagram.png");?>" alt="Instagram" title="Instagram" _secure="true"></a>
					</div>
					<?php } ?>
					<?php if($twitter){ ?>
					<div class="col-md-4 col-xs-4">
						<a href="<?php echo $twitter?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-twitter.png");?>" alt="Twitter" title="Twitter" _secure="true"></a>
					</div>
					<?php } ?>
				</div>
				<div class="row">
					<?php if($pinterest){ ?>
					<div class="col-md-4 col-xs-4">
						<a href="<?php echo $pinterest?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-pinterest.png");?>" alt="Pinterest" title="Pinterest" _secure="true"></a>
					</div>
					<?php } ?>
					<?php if($spotify){ ?>
					<div class="col-md-4 col-xs-4">
						<a href="<?php echo $spotify?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-spotify.png");?>" alt="Spotify" title="Spotify" _secure="true"></a>
					</div>
					<?php } ?>
					<?php if($youtube){ ?>
					<div class="col-md-4 col-xs-4">
						<a href="<?php echo $youtube?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-youtube.png");?>" alt="Youtube" title="Youtube" _secure="true"></a>
					</div>
					<?php } ?>
				</div>
            </div>
			<div class="col-sm-3 col-12 footer-resources">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sol_footer_links1')->toHtml();?>
            </div>
			<div class="col-sm-3 col-12 footer-about">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sol_footer_links2')->toHtml();?>
            </div>
			<div class="col-sm-3 col-12 footer-contact">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sol_footer_links3')->toHtml();?>
            </div>
		</div>
		<div class="footer-bottom row">
			<div class="footer-bottom-content">
				<span>
					<p><?= /* @escapeNotVerified */ $block->getCopyright() ?></p>
					<!--<a class="footer-bottom-link-1" href="/<?php echo $privacy;?>"><?php echo __('Privacy Policy')?></a>-->
					<a class="footer-bottom-link-2" href="/<?php echo $terms;?>"><?php echo __('Terms of Use')?></a>
				</span>
			</div>
		</div>
	</div>
</div>