<?php
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$storeName = $_helperCdi->getStoreConfig('general/store_information/name');
$storePhone = $_helperCdi->getStoreConfig('general/store_information/phone');
$storeZip = $_helperCdi->getStoreConfig('general/store_information/postcode');
$storeStreet1 = $_helperCdi->getStoreConfig('general/store_information/street_line1');
$storeStreet2 = $_helperCdi->getStoreConfig('general/store_information/street_line2');
$storeDisclaimer = $_helperCdi->getStoreConfig('general/store_information/disclaimer');
$sitemap = $_helperCdi->getStoreConfig('general/store_information/sitemap');
$contacts = $_helperCdi->getStoreConfig('general/store_information/contacts');
$terms = $_helperCdi->getStoreConfig('general/store_information/termsofuse');
$privacy = $_helperCdi->getStoreConfig('general/store_information/privacypolicy');
?>
<div class="footer">
    <div class="container">
		<div class="footer-top row">
			<div class="col-md-3 col-12 footer-social">
				<h4><?php echo __('SOL REPUBLIC')?></h4>
				<div class="row">
					<div class="col-md-4 col-xs-4">
						<a href="https://www.facebook.com/solrepublic" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-facebook.png");?>" alt="Facebook" title="Facebook" _secure="true"></a>
					</div>
					<div class="col-md-4 col-xs-4">
						<a href="https://www.instagram.com/SOLREPUBLIC" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-instagram.png");?>" alt="Instagram" title="Instagram" _secure="true"></a>
					</div>
					<div class="col-md-4 col-xs-4">
						<a href="https://twitter.com/SOLREPUBLIC" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-twitter.png");?>" alt="Twitter" title="Twitter" _secure="true"></a>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4 col-xs-4">
						<a href="https://www.pinterest.com/solrepublic/" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-pinterest.png");?>" alt="Pinterest" title="Pinterest" _secure="true"></a>
					</div>
					<div class="col-md-4 col-xs-4">
						<a href="https://open.spotify.com/user/solrepublic" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-spotify.png");?>" alt="Spotify" title="Spotify" _secure="true"></a>
					</div>
					<div class="col-md-4 col-xs-4">
						<a href="http://www.youtube.com/user/solrepublic" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/footer-youtube.png");?>" alt="Youtube" title="Youtube" _secure="true"></a>
					</div>
				</div>
            </div>
			<div class="col-md-3 col-12 footer-resources">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sol_footer_links1')->toHtml();?>
            </div>
			<div class="col-md-3 col-12 footer-about">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sol_footer_links2')->toHtml();?>
            </div>
			<div class="col-md-3 col-12 footer-contact">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sol_footer_links3')->toHtml();?>
            </div>
		</div>
		<div class="footer-bottom row">
			<div class="footer-bottom-content">
				<span>
					<p><?= /* @escapeNotVerified */ $block->getCopyright() ?></p>
					<a class="footer-bottom-link-1" href="/<?php echo $privacy;?>"><?php echo __('Privacy Policy')?></a>
					<a class="footer-bottom-link-2" href="/<?php echo $terms;?>"><?php echo __('Terms of Use')?></a>
				</span>
			</div>
		</div>
	</div>
</div>