<style>
        .banderas{
          color: #999999;
          text-decoration: none
        }
		.banderas > img {
		  width: 24px;
		}
       .dropdown-toggle.banderas:after{
          border-top: .6em solid;
          border-right: .6em solid transparent;
          border-bottom: 0;
          border-left: .6em solid transparent;
          margin-left: .6em;
          vertical-align: middle;
        }
        .banderas:hover{
          text-decoration: none;
          color: #999999;
          }
        .countrySelectMenu a {
            color: black;
            padding: 5px 0 5px 35px;
            display: block;
			font-size:14px;
        }
        .countrySelectMenu  a:hover{
          color: #e73c3e;
        }
        .countrySelectMenu {
          padding: 10px 20px 20px 20px;
          margin-top: 15px;
          background: #fff;
        }
        .countrySelectMenu .block-subtitle {
          color: #50A4CF;
          font-family: "Roboto", "Helvetica Neue", Verdana, Arial, sans-serif;
          font-size: 10px;
          font-weight: bold;
          line-height: 1.4;
          padding: 5px;
          text-align: center;
          text-transform: uppercase;
          margin-bottom: 0px;
        }

        .countrySelectMenu .close {
          width: 40px;
		  float: right;
		  display: block;
		  color: #999999;
		  text-decoration: none;
		  font-weight: normal;
		  font-size: 30px;
		  position: absolute;
		  top: 0;
		  right: 30px;
		}
		
		.dropdown-menu.countrySelectMenu.show {
		  transform: translate3d(-180px, 23px, 0px) !important;
		}
		
		.countrySelectMenu li a:hover{
		  text-decoration:none;
		}
		
		.country-header-wrapper {
			display: inline-block;
			position: relative;
			top: 8px;
		}
		
		@media (max-width: 768px) {

			header .account-cart-wrapper {
				position: absolute;
				top: 10px;
				right: 10px;
			}

		}


      </style>
	 
	<div class="container">
        <div class="dropdown"> 
<a class="dropdown-toggle banderas " href="#"  id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <img src="<?php echo $this->getViewFileUrl("images/mexico.jpg");?>">
          </a>
          <div class="dropdown-menu countrySelectMenu" aria-labelledby="dropdownMenuLink">
            <p class="text-center block-subtitle">SELECCIONE UN PAÍS</p>
            <a class="close skip-link-close" href="#" title="Close">×</a>
            <a class="dropdown-item" href="https://www.solrepublic.com.au/" style="background:url(<?php echo $this->getViewFileUrl("images/australia.png");?>) left center no-repeat;">Australia <span>(English)</span></a>
            <a class="dropdown-item" href="https://www.solrepublic.com/" style="background:url(<?php echo $this->getViewFileUrl("images/usa.png");?>) left center no-repeat;">USA <span>(English)</span></a>
            <a class="dropdown-item" href="https://www.solrepublic.co.uk/" style="background:url(<?php echo $this->getViewFileUrl("images/uk.png");?>) left center no-repeat;">United Kingdom <span>(UK)</span></a>
          </div>
		  </div>
		  </div>
		<script type="text/javascript">
    require(['bootstrap']);
</script>
