<div class="quick-access">
	<!--sideMenu SOLburger-->
	<a class="menuToggle SOLburger"><span class="cd-menu-icon"></span></a>
</div>

<?php
	
	jQuery(document).ready(function(){
		jQuery('.SOLburger').click(function(e){
			if(jQuery(this).hasClass("is-clicked")){
				jQuery(this).removeClass('is-clicked');
			}else{
				jQuery(this).addClass('is-clicked');
				e.preventDefault();
			}
	    });
	});

?>