<?php
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$facebook = $_helperCdi->getStoreConfig('general/store_information/facebook_link');
$instagram = $_helperCdi->getStoreConfig('general/store_information/instagram_link');
$youtube = $_helperCdi->getStoreConfig('general/store_information/youtube_link');
$twitter = $_helperCdi->getStoreConfig('general/store_information/twitter_link');
$spotify = $_helperCdi->getStoreConfig('general/store_information/spotify_link');
$pinterest = $_helperCdi->getStoreConfig('general/store_information/pinterest_link');
?>
<div class="sideMenuSocial">
	<h3><?php echo __('Follow us')?></h3>
	<div class="grid grid-pad">
		<?php if($facebook){ ?>
		<div class="col-md-2 col-xs-2">
			<div class="content">
				<a href="<?php echo $facebook?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/sideMenu-facebook.png");?>" alt="Facebook" title="Facebook" _secure="true"></a>
			</div>
		</div>
		<?php } ?>
		<?php if($instagram){ ?>
		<div class="col-md-2 col-xs-2">
			<div class="content">
				<a href="<?php echo $instagram?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/sideMenu-instagram.png");?>" alt="Instagram" title="Instagram" _secure="true"></a>
			</div>
		</div>
		<?php } ?>
		<?php if($twitter){ ?>
		<div class="col-md-2 col-xs-2">
			<div class="content">
				<a href="<?php echo $twitter?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/sideMenu-twitter.png");?>" alt="Twitter" title="Twitter" _secure="true"></a>
			</div>
		</div>
		<?php } ?>
		<?php if($pinterest){ ?>
		<div class="col-md-2 col-xs-2">
			<div class="content">
				<a href="<?php echo $pinterest?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/sideMenu-pinterest.png");?>" alt="Pinterest" title="Pinterest" _secure="true"></a>
			</div>
		</div>
		<?php } ?>
		<?php if($spotify){ ?>
		<div class="col-md-2 col-xs-2">
			<div class="content">
				<a href="<?php echo $spotify?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/sideMenu-spotify.png");?>" alt="Spotify" title="Spotify" _secure="true"></a>
			</div>
		</div>
		<?php } ?>
		<?php if($youtube){ ?>
		<div class="col-md-2 col-xs-2">
			<div class="content">
				<a href="<?php echo $youtube?>" target="_blank"><img src="<?php echo $this->getViewFileUrl("images/social/sideMenu-youtube.png");?>" alt="Youtube" title="Youtube" _secure="true"></a>
			</div>
		</div>
		<?php } ?>
	</div>
</div>