<div class="sideMenuSocial">
	<h3><?php echo __('Follow us')?></h3>
	<div class="grid grid-pad">
		<div class="col-1-6">
			<div class="content">
				<a href="https://www.facebook.com/solrepublic" target="_blank">
					<img src="https://www.solrepublic.com/skin/frontend/enterprise/solrepublic_2017/images/social_icons/sideMenu-facebook.png" alt="Facebook" title="Facebook" _secure="true">
				</a>
			</div>
		</div>
		<div class="col-1-6">
			<div class="content">
				<a href="http://instagram.com/SOLREPUBLIC" target="_blank">
					<img src="https://www.solrepublic.com/skin/frontend/enterprise/solrepublic_2017/images/social_icons/sideMenu-instagram.png" alt="Instagram" title="Instagram" _secure="true">
				</a>
			</div>
		</div>
		<div class="col-1-6">
			<div class="content">
				<a href="https://twitter.com/SOLREPUBLIC" target="_blank">
					<img src="https://www.solrepublic.com/skin/frontend/enterprise/solrepublic_2017/images/social_icons/sideMenu-twitter.png" alt="Twitter" title="Twitter" _secure="true">
				</a>
			</div>
		</div>
		<div class="col-1-6">
			<div class="content">
				<a href="https://www.pinterest.com/solrepublic/" target="_blank">
					<img src="https://www.solrepublic.com/skin/frontend/enterprise/solrepublic_2017/images/social_icons/sideMenu-pinterest.png" alt="Pinterest" title="Pinterest" _secure="true">
				</a>
			</div>
		</div>
		<div class="col-1-6">
			<div class="content">
				<a href="https://play.spotify.com/user/solrepublic/playlist/3WHlTCSchhLYGMJ0LpG5sc" target="_blank">
					<img src="https://www.solrepublic.com/skin/frontend/enterprise/solrepublic_2017/images/social_icons/sideMenu-spotify.png" alt="Spotify" title="Spotify" _secure="true">
				</a>
			</div>
		</div>
		<div class="col-1-6">
			<div class="content">
				<a href="http://www.youtube.com/user/solrepublic" target="_blank">
					<img src="https://www.solrepublic.com/skin/frontend/enterprise/solrepublic_2017/images/social_icons/sideMenu-youtube.png" alt="Youtube" title="Youtube" _secure="true">
				</a>
			</div>
		</div>
	</div>
</div>