<div id="sideMenu" class="sideMenu" style="right: -100%; display:none">
	<div class="sideMenuPad">
		<a class="menuToggle SOLburger inmenu">
			<span class="cd-menu-icon"></span>
		</a>
		<div class="sideMenuNav">
			<div class="navContainer sideNav">
				<?php echo $block->getChildHtml('tooglevav_tooglenav') ?>
			</div>
		</div>
		<?php echo $block->getChildHtml('customer_options') ?>
		<?php echo $block->getChildHtml('tooglevav_social') ?>
	</div>
</div>