<?php
/**
 * Copyright © 2016 Mageplaza. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /* @var $block \Intcomex\ScheduledReindex\Block\System\Config\Collect */ ?>

<script>
    require([
        'jquery'
    ], function($) {

        $('#collect_button').click(function () {

            let collectSpan = $('#collect_span');
            let params = {
                enabled  : parseInt($("#reindex_general_enabled").val()),
                php_path : $("#reindex_general_php_path").val(),
                cron     : $("#reindex_general_cron").val()
            };
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters   : params,
                loaderArea   : false,
                asynchronous : true,
                onCreate: function() {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    $('#collect_message_span').text('');
                },
                onSuccess: function(response) {
                    let resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else if(!response.responseJSON.success) {
                        resultText = response.responseJSON.message;
                        collectSpan.find('.collected').hide();
                    } else if (response.status === 200) {
                        if (response.responseJSON.crontab) {
                            let crontabDiv = $('#crontab');
                            let cronLines = response.responseJSON.crontab.split('\n');
                            crontabDiv.empty().append('<h2>Jobs</h2><hr>');
                            for (let i = 0; i < cronLines.length; i++) {
                                if (cronLines[i]) {
                                    crontabDiv.append('<p>' + cronLines[i] + '</p>');
                                }
                            }
                            crontabDiv.append('<hr>').show();
                        }
                        resultText = response.responseJSON.message;
                        collectSpan.find('.collected').show();
                    }
                    $('#collect_message_span').text(resultText);
                    collectSpan.find('.processing').hide();
                }
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
<span class="collect-indicator" id="collect_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="collect_message_span"></span>
</span>
<div id="crontab" style="display: none; margin-top: 20px"></div>
