<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<section class="contact-page">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <img src="http://sitiobase03.ariadna.co/pub/static/version1561752581/frontend/Cdi/marley/es_CO/images/contacto.jpg" alt="" title="">
      </div>
      <div class="col-md-6">
        <div class="page-title">
          <h1>Contáctenos</h1>
        </div>
        <form action="<?= $block->escapeUrl($block->getFormAction()) ?>" id="contactForm" method="post">
          <div class="fieldset">
            <h2 class="legend">Información de Contacto</h2>
            <ul class="form-list">
              <li class="fields">
                <div class="field">
                  <label for="name" class="required">Nombre</label>
                  <div class="input-box">
                    <input name="name" id="name" title="Nombre" value="" class="input-text required-entry" type="text" required>
                  </div>
                </div>
                <div class="field">
                  <label for="email" class="required">Correo electrónico</label>
                  <div class="input-box">
                    <input name="email" id="email" title="Correo electrónico" value="" class="input-text required-entry validate-email" type="email" required>
                  </div>
                </div>
              </li>
              <li>
                <label for="telephone">Teléfono</label>
                <div class="input-box">
                  <input name="telephone" id="telephone" title="Teléfono" value="" class="input-text" type="number">
                </div>                
              </li>
              <li>
              <label for="subject" class="required"><span><?= $block->escapeHtml(__('Subject')) ?></label>
                <div class="input-box">
                  <input name="subject" id="subject" title="subject" value="" class="input-text" type="text" maxlength="80" style="width: 535px;" required>
                </div>
              </li>
              <li class="wide">
                <label for="comment" class="required">Comentario</label>
                <div class="input-box">
                <textarea name="comment" id="comment" title="Comentario" class="required-entry" cols="5" rows="3" required></textarea>
                </div>
              </li>
            </ul>
          </div>
          <?= $block->getChildHtml('form.additional.info') ?>
          <div class="buttons-set">
            <p class="required">* Campos Requeridos</p>
            <button type="submit" title="Enviar" class="button"><span><span>Enviar</span></span></button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>