<?php
$_helperCdi = $this->helper(Cdi\Custom\Helper\Data::class);
/** @var \Cdi\Custom\Helper\Data $_helperCdi */
$websiteCode = $_helperCdi->getWebsideCode();
?>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($websiteCode . '_free_shipping_en')->toHtml();?>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($websiteCode . '_free_shipping_es')->toHtml();?>
