<?php

/**
 * @var $block \MagicToolbox\MagicZoomPlus\Block\Product\View\Gallery
 */
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$_product = $block->getProduct();
$discount = $_helperCdi->getDiscount($_product);

$helperGallery = $this->helper('Intcomex\GridImages\Helper\Data');
$type = $helperGallery->getViewGallery();
?>
<?php if ($discount != 0): 
    $discount = 100 - $discount; ?>
    <span class="product-tag disccount-tag">-<?php echo $discount ?>%</span>
<?php endif; ?>
<?php if ($_helperCdi->isNew($_product)): ?>
    <span class="product-tag new-tag"><?php /* @escapeNotVerified */ echo __('New') ?></span>
<?php endif; ?>
<?php if ($_product->getTypeId() == 'virtual'): ?>
    <span class="product-tag download-tag"></span>
<?php endif; ?>
<?php if ($_helperCdi->checkBestseller($_product)): ?>
    <span class="product-tag bestseller-tag"></span>
<?php endif;

if($type == "grid"){
    echo $this->getLayout()->createBlock("Magento\Catalog\Block\Product\View\Gallery")->setTemplate("Intcomex_GridImages::product/view/gallery.phtml")->toHtml();
}else{    
    echo $block->getRenderedHtml();
}

