<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
	<div class="container">
		<div class="message info empty text-center"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
	</div>
<?php else: ?>
	<div style="display:none">
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
	</div>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-products">
		<div class="container products-list" id="products-list">
			<?php $count = 0;?>
			<?php foreach ($_productCollection as $_product): ?>
				<div class="row item  lightBG <?php echo ($count % 2 == 0) ? 'odd' : 'even'; ?>">
					<?php $count++; ?>
					<div class="secContain">
						<?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
						<div class="productImageContain col-md-6 xs-12">
							<?php
							$productImage = $block->getImage($_product, $imageDisplayArea);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
							<a href="<?php echo $_product->getProductUrl()?>" title="<?php echo $_productNameStripped;?>" class="product-image">
								<?= $productImage->toHtml() ?>
							</a>
						</div>
						<div class="product-shop col-md-6 xs-12">
							<div class="f-fix">
								<h2 class="product-name">
									<a href="<?php echo $_product->getProductUrl()?>" title="<?php echo $_productNameStripped;?>">
										<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
									</a>
								</h2>
								<div class="desc std">
									<?php echo $_helper->productAttribute($_product, $_product->getDescription(), 'description') ?>

									<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
        							
									<a class="buy-now SOLbtn" href="<?php echo $_product->getProductUrl()?>"><?php echo __('Explore')?></a>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
    <div style="display:none">
	<?= $block->getToolbarHtml() ?>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
