<?php
/** 
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/**
 * @var $block \Manadev\LayeredNavigation\Blocks\Navigation
 *
 * Based on app/code/Magento/LayeredNavigation/view/frontend/templates/layer/view.phtml (diff to check
 * what has changed).
 */
$filter = true;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$categoryCurrent = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
if(!empty($categoryCurrent)){
  $producCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
  $collection = $producCollection->create();
  $collection->addAttributeToSelect('entity_id');
  $collection->addCategoriesFilter(['in' => $categoryCurrent->getId()]);
  $products = $collection->getData();
  if(empty($products)){
    $filter = false;
  }
}

?>

<?php if ($block->isVisible()&&$filter==true): ?>
    <div class="block filter mana-filter-block mana-intcomex" data-mage-init='{ "Manadev_LayeredNavigation/js/NavigationView": {} }'>
        <!--<div class="block-title filter-title">
            <strong><?php echo __('Shop By') ?></strong>
        </div>-->

        <div class="block-content filter-content">
            <?php if ($block->hasState() && $block->isAppliedFilterVisible()) : ?>
                <div class="filter-current">
                    <strong class="block-subtitle filter-current-subtitle" role="heading" aria-level="2" data-count="<?php echo $block->getAppliedOptionCount() ?>"><?php echo __('Now Shopping by') ?></strong>
                    <ol class="items">
                        <?php foreach ($block->getAppliedFilters() as $engineFilter): ?>
                            <?php foreach ($engineFilter->getAppliedItems() as $item) : ?>
                                <li class="item"><?php echo $block->renderAppliedItem($engineFilter, $item) ?></li>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    </ol>
                </div>

                <div class="block-actions filter-actions">
                    <a href="<?php echo $block->getClearUrl() ?>"<?php echo $block->getClearLinkAttributes() ?> class="action clear filter-clear"><span><?php echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>

            <!--<strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php echo __('Shopping Options') ?>
                <?php echo $block->getApplyHtml() ?>
            </strong>-->

            <div class="filter-options" id="narrow-by-list">
              <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                <?php foreach ($block->getFilters() as $key => $filter): ?>
                  <?php $cssClass = $block->getData('css_prefix') . '-filter-' . str_replace('_', '-', $filter->getFilter()->getData('param_name')) ?>
                  <div class="panel-heading">
                    <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $key ?>"><?php echo $block->escapeHtml(__($filter->getName())) ?></a>
                    </h4>
                  </div>
                  <div id="collapse<?php echo $key ?>" class="panel-collapse collapse">
                    <div class="panel-body">
                      <?php echo $block->renderFilter($filter) ?>
                    </div>
                  </div>
                <?php endforeach; ?>
                </div>
              </div>
            </div>
        </div>
    </div>
<?php endif; ?>
