<?php
/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
$total = $block->getItems()->getSize();
/* @var $compareHelper Magento\Catalog\Helper\Product\Compare */
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
?>
<div class="container" id="floatingComparisonBar">
    <?php if ($total): ?>
        <div class="row" style="display:flex; width: auto;">
            <?php if ($block->getData('isLimitReached')): ?>
                <span><?= /* @escapeNotVerified */ __('Ya tienes 4 productos para comparar.') ?></span>
            <?php elseif ($block->getData('isNotSameCategory')): ?>
                <span><?= /* @escapeNotVerified */ __('No se puede agregar un producto de otra categoría. Elimina los productos actuales para comparar una nueva categoría.') ?></span>
            <?php else: ?>
                <?php $index = 0; ?>
                <?php $count = 0; ?>
                <?php $helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
                <?php /** @var $item \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($block->getItems() as $item): ?>
                    <?php $count++; ?>
                    <?php if ($count > 2) : ?>
                        <?php $classCom = "carr-two";?>
                    <?php else : ?>
                        <?php $classCom = "carr-one";?>  
                    <?php endif; ?>
                    <div class="item product product-item col-md-2 <?php /* @escapeNotVerified */ echo $classCom; ?>">
                        <a href="#" data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataRemove($item) ?>' class="action delete" title="<?= /* @escapeNotVerified */ __('Remove Product') ?>">
                            <span><?= /* @escapeNotVerified */ __('Remove Product') ?></span>
                        </a>
                        <a class="product-item-photo" href="<?= /* @escapeNotVerified */ $block->getProductUrl($item) ?>" title="<?= /* @escapeNotVerified */ $block->stripTags($item->getName(), null, true) ?>">
                            <?= $block->getImage($item, 'product_comparison_list')->toHtml() ?>
                        </a>
                        <strong class="product-item-name">
                            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($item) ?>" title="<?= /* @escapeNotVerified */ $block->stripTags($item->getName(), null, true) ?>">
                                <?= /* @escapeNotVerified */ $helper->productAttribute($item, $item->getName(), 'name') ?>
                            </a>
                        </strong>
                    </div>
                <?php endforeach; ?>
                <?php for ($i = 1; $i <= (4 - $total); $i++) : ?>
                    <?php if ($total > 2) : ?>
                        <?php $classCom = "carr-two";?>
                    <?php else : ?>
                        <?php if ($total == 2) : ?>
                            <?php $classCom = "carr-two";?>
                        <?php else : ?>
                            <?php if ($i == 1) : ?>
                                <?php $classCom = "carr-one";?>
                            <?php else : ?>
                                <?php $classCom = "carr-two";?>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <div class="item product product-item col-md-2 <?php /* @escapeNotVerified */ echo $classCom; ?>">
                        <strong class="product-item-name">
                            <span><?= /* @escapeNotVerified */ __('Agregar producto') ?></span>
                        </strong>
                    </div>
                <?php endfor; ?>
                <div class="item product product-item col-md-2">
                    <form action="<?= /* @escapeNotVerified */ $block->getUrl('catalog/product_compare/removeall') ?>" method="post" class="remove-all">
                        <button class="action-close" data-role="closeBtn" type="submit">
                            <span><?= /* @escapeNotVerified */ __('Close') ?></span>
                        </button>
                    </form>
                    <p style="display: flex; justify-content: center; width: 100%;"><?= /* @escapeNotVerified */ $total === 1 ? __("$total producto seleccionado") : __("$total productos seleccionados") ?></p>
                    <form action="<?= /* @escapeNotVerified */ $block->getUrl('catalog/product_compare') ?>">
                        <button type="submit" title="<?= /* @escapeNotVerified */ __('Comparar') ?>" class="action tocart primary compare-button" <?= $total === 1 ? 'disabled' : '' ?> >
                            <span><?= /* @escapeNotVerified */ __('Comparar') ?></span>
                        </button>
                    </form>
                </div>
            <?php endif; ?>
        </div>
        <dots id="dots">
            <div class="dot dot-one"></div>
            <div class="dot dot-two"></div>
        </dots>
    <?php endif; ?>
</div>
<script type="text/x-magento-init">
    {
        "body": {
            "intcomex/ajaxcompare" : {
                "total": <?= /* @noEscape */ $total ?>
            }
        }
    }
</script>
