<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    default:
        $exist = null;
}
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$reviewFactory = $objectManager->create('Magento\Review\Model\Review');
$blockList = $block->getLayout()->createBlock('Magento\CatalogWidget\Block\Product\ProductsList');
$blockList2 = $block->getLayout()->createBlock('Mageplaza\Productslider\Block\BestSellerProducts');

?>

<?php if ($exist):?>
    <section class="block widget block-products-list grid">
        <div class="container">
            <div class="row">
                <div class="header-section col-xs-12">
                    <h2 class="title-section"><?= /* @escapeNotVerified */ $title ?></h2>
                </div>

                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?php if ($type == 'related'): ?>
                        <div class="block-content col-xs-12 block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
                    <?php else: ?>
                        <div class="block-content col-xs-12 block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
                    <?php endif; ?>
                <?php else: ?>
                    <div class="block-content col-xs-12 block <?= /* @escapeNotVerified */ $class ?>">
                <?php endif; ?>
                    <?php if ($type == 'related' && $canItemsAddToCart && false): ?>
                        <div class="block-actions">
                            <?= /* @escapeNotVerified */ __('Check items to add to the cart or') ?>
                            <button type="button" class="action select" role="button"><span><?= /* @escapeNotVerified */ __('select all') ?></span></button>
                        </div>
                    <?php endif; ?>
                    <div class="products-grid grid products-<?= /* @escapeNotVerified */ $type ?>">
                        <?php $iterator = 1; ?>
                        <ul class="owl-carousel product-items products-<?= /* @escapeNotVerified */ $type ?>"> 
                        <?php foreach ($items as $_item): ?>
                            <?php $discount = $_helperCdi->getDiscount($_item);?>
                        
                            <?= ($iterator++ == 1) ? '<li class="item"">' : '</li><li class="item"">' ?>
                    <div class="product-item-info">
                        <a href="<?= $block->getProductUrl($_item) ?>"
                           class="product-item-photo">
                            <?= $block->getImage($_item, 'recently_viewed_products_grid_content_widget')->toHtml(); ?>
                        </a>
                        <?php if ($discount != 0): 
                            $discount = 100 - $discount; ?>
                            <span class="product-tag disccount-tag">-<?php echo $discount ?>%</span>
                        <?php endif; ?>
                        <?php if ($_helperCdi->isNew($_item)): ?>
                            <span class="product-tag new-tag"><?php /* @escapeNotVerified */ echo __('New') ?></span>
                        <?php endif; ?>
                        <?php if ($_item->getTypeId() == 'virtual'): ?>
                            <span class="product-tag download-tag"></span>
                        <?php endif; ?>
                        <?php if ($_helperCdi->checkBestseller($_item)): ?>
                            <span class="product-tag bestseller-tag"></span>
                        <?php endif; ?>
                        <div class="product-item-details product-info_main">
                            <?php if ($blockList2->canShowReview()) : ?>
                                <?php $reviewFactory->getEntitySummary($_item, $_item->getStore()->getId());
                                $ratingSummary = (int)$_item->getRatingSummary()->getRatingSummary(); ?>
                                <div class="rating-summary item" itemprop="reviewRating" itemscope="" >
                                    <div class="rating-result" title="<?php echo $ratingSummary; ?>%">
                                        <meta itemprop="worstRating" content="1">
                                        <meta itemprop="bestRating" content="100">
                                        <span style="width:<?php echo $ratingSummary; ?>%">
                                            <span itemprop="ratingValue"><?php echo $ratingSummary; ?>%</span>
                                        </span>
                                    </div>
                                </div>
                            <?php endif; ?>

                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                   href="<?= $block->getProductUrl($_item) ?>"
                                   class="product-item-link product-name">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>

                            <?php if ($blockList2->canShowPrice()) : ?>
                                <?= $blockList2->getProductPrice($_item); ?>
                            <?php endif; ?>

                            <div class="product-item-actions">
                                <?php if ($blockList2->canShowAddToCart()) : ?>
                                    <div class="actions-primary">
                                        <?php if ($_item->isSaleable()) : ?>
                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) : ?>
                                                <button class="action tocart primary mageplaza-product-slider-button"
                                                        data-mage-init='{"redirectUrl": {"url": "<?= $block->getAddToCartUrl($_item) ?>"}}'
                                                        type="button" title="<?= __('Add to Cart') ?>">
                                                    <span><?= __('Add to Cart') ?></span>
                                                </button>
                                            <?php else : ?>
                                                <?php $postParams = $blockList->getAddToCartPostParams($_item); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                                    <?php echo $block->getBlockHtml('formkey')?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php endif; ?>
                                        <?php else : ?>
                                            <?php if ($_item->getIsSalable()) : ?>
                                                <div class="stock available">
                                                    <span><?= __('In stock') ?></span></div>
                                            <?php else : ?>
                                                <div class="stock unavailable">
                                                    <span><?= __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <div class="actions-secondary" data-role="add-to-links">
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                            data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                            class="action towishlist" data-action="add-to-wishlist"
                                            title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?= ($iterator === count($items) + 1) ? '</li>' : '' ?>


                        <?php endforeach ?>
                        </ul>
                    </div>
                </div>
                <!--<script>
                    require(['jquery', 'mageplaza/core/owl.carousel'], function ($) {
                        $('.owl-carousel.product-items.products-<?= /* @escapeNotVerified */ $type ?>').owlCarousel(<?= $blockList2->getAllOptions()?>);
                    });
                </script>
                -->
                <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {}
                    }
                }
                </script>
            </div>
        </div>
    </section>

<?php endif;?>
