<?php
$incrementId = $block->getRealOrderId();
$orderId = $block->getOrderId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$order = $objectManager->create('\Magento\Sales\Model\OrderRepository')->get($orderId);
$billingAddress = $order->getBillingAddress();
// Get Order Payment
$payment = $order->getPayment();
$status = $payment->getAdditionalInformation()['paymentResponse']["status"];
$method = $payment->getAdditionalInformation()['method'];
if($status == 'rejected' && $method == 'mercadopago_custom'){
?>
<main id="maincontent" class="page-main"><a id="contentarea" tabindex="-1"></a>
    <div class="page-title-wrapper">
        <p><img class="ico-page-title" style="width: auto!important" src="<?php echo $block->getUrl("pub/media/")?>error.png"></p>
        <h1 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper">¡No recibimos tu pago!</span>
        </h1>
        <h2>Tu pedido fue rechazado</h2>
    </div>
    <div class="page messages">
        <div data-placeholder="messages"></div>
        <div data-bind="scope: 'messages'">
        <!-- ko if: cookieMessages && cookieMessages.length > 0 --><!-- /ko -->
        <!-- ko if: messages().messages && messages().messages.length > 0 --><!-- /ko -->
        </div>
    </div>
    <div class="columns">
        <div class="column main">
            <div class="container">
                <p>Tu compra no se ha finalizado debido algún problema en la autorización de pago</p>
                <p>Es posible que haya llenado algunos datos de forma incorrecta o puede haber habido<br>
                algún problema con la tarjeta en caso de compra con tarjeta</p>
            
                <div class="actions-toolbar">
                    <div class="primary">
                        <?= $block->escapeHtml(
                            __('<a href="%1" class="action primary" type="submit" title="Imprimir Pagoefectivo"><span>Retoma tu compra y verifica los datos o selecciona otro medio de pago</span></a>', $block->escapeUrl($block->getContinueShoppingUrl())),
                            ['a']
                        ) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<?php }elseif($status == 'in_process' && $method == 'mercadopago_custom') {?>
<main id="maincontent" class="page-main"><a id="contentarea" tabindex="-1"></a>
    <div class="page-title-wrapper">
        <p><img class="ico-page-title" style="width: auto!important" src="<?php echo $block->getUrl("pub/media/")?>espera.png"></p>
        <h1 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper">¡Estamos procesando tu pago!</span>
        </h1>
        <h2>Tu pedido esta en espera</h2>
    </div>
    <div class="page messages"><div data-placeholder="messages"></div>
        <div data-bind="scope: 'messages'">
        <!-- ko if: cookieMessages && cookieMessages.length > 0 --><!-- /ko -->
        <!-- ko if: messages().messages && messages().messages.length > 0 --><!-- /ko -->
        </div>
    </div>
    <div class="columns">
        <div class="column main">
            <div class="container">
                <p>Tu número de pedido es <strong><?php echo $incrementId; ?></strong></p>
                <p>Tu compra esta en espera, estamos esperando la autorización de pago</p>
                <p>Si tu pago es aprobado te enviaremos un correo electrónico de confirmación a <strong><?php echo $billingAddress->getEmail(); ?></strong><br>con los detalles e información de envío.</p>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action primary" type="submit" title="Imprimir Pagoefectivo">
                            <span>Continuar comprando</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<?php } ?>