<?php
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$storeName = $_helperCdi->getStoreConfig('general/store_information/name');
$storePhone = $_helperCdi->getStoreConfig('general/store_information/phone');
$storeZip = $_helperCdi->getStoreConfig('general/store_information/postcode');
$storeStreet1 = $_helperCdi->getStoreConfig('general/store_information/street_line1');
$storeStreet2 = $_helperCdi->getStoreConfig('general/store_information/street_line2');
$storeDisclaimer = $_helperCdi->getStoreConfig('general/store_information/disclaimer');
$sitemap = $_helperCdi->getStoreConfig('general/store_information/sitemap');
$contacts = $_helperCdi->getStoreConfig('general/store_information/contacts');
$terms = $_helperCdi->getStoreConfig('general/store_information/termsofuse');
$privacy = $_helperCdi->getStoreConfig('general/store_information/privacypolicy');
?>
<a id="scroll-to-top" href="#top" class="show" title="Back to top">
	<div class="b2tArrow"><?php echo __('Back to top')?></div>
</a>
<div class="footer-bottom">
    <div class="container">
		<div class="row">
			<div class="col-md-4 col-12 footer-address text-left">
				<span class="icon"></span>
				<div class="address-info">
					<h5><?php echo $storeName;?></h5>
					<?php echo $storeStreet1;?><br/>
					<?php echo $storeStreet2;?><br/>
					<?php echo $storeZip;?>
				</div>
            </div>
			<div class="col-md-4 col-12 footer-contacts text-left">
				<span class="icon"></span>
				<div class="contact-info">
					<h5><?php echo __('Need Help?');?></h5>
					<a href="tel:<?php echo $storePhone;?>"><?php echo $storePhone;?></a> / <a href="/<?php echo $contacts?>"><?php echo __('Email Jam');?></a>
				</div>
            </div>
		</div>
		<div class="row">
			<div class="col-md-12 col-12 footer-legal">
				<p id="disclaimer"><?php echo $storeDisclaimer; ?></p>
				<p><?= /* @escapeNotVerified */ $block->getCopyright() ?></p>
                <p>
					<strong><a href="/<?php echo $sitemap;?>"><?php echo __('Site Map')?></a></strong>
					<strong><a href="/<?php echo $privacy;?>"><?php echo __('Privacy Policy')?></a></strong>  
					<strong><a href="/<?php echo $terms;?>"><?php echo __('Terms of Use')?></a></strong>
				</p>
			</div>
		</div>
	</div>
</div>