<a id="scroll-to-top" href="#top" class="show" title="Back to top">
	<div class="b2tArrow"><?php echo __('Back to top')?></div>
</a>
<div class="footer-bottom">
    <div class="container">
		<div class="row">
			<div class="col-md-4 col-12 footer-address text-left">
				<span class="icon"></span>
				<div class="address-info">
					<h5>JAM USA</h5>
					3000 Pontiac Trail<br>
					Commerce Township, MI<br>
					48390 USA
				</div>
            </div>
			<div class="col-md-4 col-12 footer-contacts text-left">
				<span class="icon"></span>
				<div class="contact-info">
					<h5>Need Help?</h5>
					<a href="tel:1-888-802-0040">1-888-802-0040</a> / <a href="/contacts">Email Jam</a>
				</div>
            </div>
		</div>
		<div class="row">
			<div class="col-md-12 col-12 footer-legal">
				<p id="disclaimer">Due to continuous product improvements, the images on the website may differ slightly <br> from the actual product that you receive.</p>
				<p><?= /* @escapeNotVerified */ $block->getCopyright() ?></p>
                <p>
					<strong><a href="/catalog/seo_sitemap/category">Site Map</a></strong>
					<strong><a href="/privacy-policy">Privacy Policy</a></strong>  
					<strong><a href="/terms-of-use">Terms of Use</a></strong>
				</p>
			</div>
		</div>
	</div>
</div>

<!--Custom Js-->
<link src="js/main.min.js"/>