<?php
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$facebook = $_helperCdi->getStoreConfig('general/store_information/facebook_link');
$instagram = $_helperCdi->getStoreConfig('general/store_information/instagram_link');
$youtube = $_helperCdi->getStoreConfig('general/store_information/youtube_link');
$twitter = $_helperCdi->getStoreConfig('general/store_information/twitter_link');
?>
<a id="scroll-to-top" href="#top" class="" title="Back to top">
	<div class="b2tArrow"><?php echo __('Back to top')?></div>
</a>
<div class="footer-top">
    <div class="footer cms-grid">
		<div class="container"> 
			<div class="row">
				<div class="col-md-6 col-12 col-md-offset-3 text-center footer-email">
					<h3><?= $block->escapeHtml(__('Connect with JAM')) ?></h3>
					<div class="block newsletter">
						<form class="form subscribe"
							novalidate
							action="<?=$block->getBaseUrl() ?>newsletter/subscriber/new/"
							method="post"
							data-mage-init='{"validation": {"errorClass": "mage-error"}}'
							id="newsletter-validate-detail">
							<div class="block-content">
								<div class="input-box field newsletter">
									<label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
									<div class="control">
										<input name="email" type="email" id="newsletter"
											   placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
											   data-mage-init='{"mage/trim-input":{}}'
											   data-validate="{required:true, 'validate-email':true}"/>
									</div>
								</div>
								<div class="actions">
									<button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
										<span><?= $block->escapeHtml(__('Subscribe')) ?></span>
									</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-2 col-12 text-left footer-country">
				</div>
				<div class="col-md-8 col-12 text-left footer-nav">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('jam_footer_top_links')->toHtml();?>
				</div>
				<div class="col-md-2 col-12 text-left footer-social">
					<ul class="social-icons">
						<?php if($facebook){ ?>
						   <li>
								<a href="<?php echo $facebook;?>" target="_blank">
									<img src="<?php echo $this->getViewFileUrl("images/social/facebook.svg");?>" alt="Facebook" />
								</a>
							</li>
						<?php } ?>
						<?php if($twitter){ ?>
							<li>
								<a href="<?php echo $twitter;?>" target="_blank">
									<img src="<?php echo $this->getViewFileUrl("images/social/twitter.svg");?>" alt="Twitter" />
								</a>
							</li>
						<?php } ?>
						<?php if($youtube){ ?>
							<li>
								<a href="<?php echo $youtube;?>" target="_blank">
									<img src="<?php echo $this->getViewFileUrl("images/social/youtube.svg");?>" alt="YouTube" />
								</a>
							</li>
						<?php } ?>
						<?php if($instagram){ ?>
							<li>
								<a href="<?php echo $instagram;?>" target="_blank">
									<img src="<?php echo $this->getViewFileUrl("images/social/instagram.svg");?>" alt="Instagram" />
								</a>
							</li>
						<?php } ?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>