<a href="#nav-wrapper-mobile" class="skip-link skip-nav">
	<span class="icon ic ic-menu"></span>
	<span class="label"><?php echo __('Menú') ?></span>
</a>
<a href="#search-wrapper-mobile" class="skip-link skip-search">
	<span class="icon ic ic-search"></span>
	<span class="label"><?php echo __('Búsqueda') ?></span>
</a>
<a href="#user-menu-wrapper-mobile" class="skip-link skip-account">
	<span class="icon ic ic-user"></span>
	<span class="label"><?php echo __('Mi cuenta') ?></span>
</a>