<?php
/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */
/* @var $compareHelper Magento\Catalog\Helper\Product\Compare */
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
$prechecked = in_array($block->getProduct()->getId(), $compareHelper->getItemCollection()->getAllIds()) ? 'checked' : '';
?>

<input
    type="checkbox"
    class="add-to-compare"
    href="#"
    title="<?= $block->escapeHtml(__('Comparar')) ?>"
    aria-label="<?= $block->escapeHtml(__('Comparar')) ?>"
    data-post='<?= /* @escapeNotVerified */ $block->getCompareHelper()->getPostDataParams($block->getProduct()) ?>'
    <?= /* @escapeNotVerified */ $prechecked ?>
    role="button">
    <?= /* @escapeNotVerified */ __('Comparar') ?>
