<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
    $reviewFactory = $objectManager->create('Magento\Review\Model\Review');
    $currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
    $currency = $currencysymbol->getStore()->getCurrentCurrencyCode();
?>
    <!--<section class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <div class="container">
            <div class="row">-->
                <div class="header-section col-xs-12">
                    <?php if ($title):?>
                    <h2 class="title-section"><?php /* @escapeNotVerified */ echo $title; ?></h2>
                </div>
                <?php endif ?>
                <div class="block-content col-xs-12">
                    <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                    <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                        <ul class="owl-carousel product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item):                              
                                $discount = $_helperCdi->getDiscount($_item);
                            ?>                            
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item">' : '</li><li class="item">' ?>
                                <div class="product-item-info">
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                    </a>
                                    <?php if ($discount != 0): 
                                        $discount = 100 - $discount; ?>
                                        <span class="product-tag disccount-tag">-<?php echo $discount ?>%</span>
                                    <?php endif; ?>
                                    <?php if ($_helperCdi->isNew($_item)): ?>
                                        <span class="product-tag new-tag"><?php /* @escapeNotVerified */ echo __('New') ?></span>
                                    <?php endif; ?>
                                    <?php if ($_item->getTypeId() == 'virtual'): ?>
                                        <span class="product-tag download-tag"></span>
                                    <?php endif; ?>
                                    <?php if ($_helperCdi->checkBestseller($_item)): ?>
                                        <span class="product-tag bestseller-tag"></span>
                                    <?php endif; ?>
                                    <div class="product-item-details product-info_main">
                                        <?php $reviewFactory->getEntitySummary($_item, $_item->getStore()->getId());
                                        $ratingSummary = (int)$_item->getRatingSummary()->getRatingSummary(); ?>
                                        <div class="rating-summary" itemprop="reviewRating" itemscope="" >
                                            <div class="rating-result" title="<?php echo $ratingSummary; ?>%">
                                                <meta itemprop="worstRating" content="1">
                                                <meta itemprop="bestRating" content="100">
                                                <span style="width:<?php echo $ratingSummary; ?>%">
                                                    <span itemprop="ratingValue"><?php echo $ratingSummary; ?>%</span>
                                                </span>
                                            </div>
                                        </div>
                                        <strong class="product-item-name">
                                            <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                               href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                               class="product-item-link product-name">
                                                <?php echo $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <?php
                                        echo $block->getProductPriceHtml($_item, $type);
                                        ?>
                                        
                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) : ?>
                                                                <button class="action tocart primary mageplaza-product-slider-button"
                                                                        data-mage-init='{"redirectUrl": {"url": "<?= $block->getAddToCartUrl($_item) ?>"}'
                                                                        type="button" title="<?= __('Add to Cart') ?>">
                                                                    <span><?= __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else : ?>
																<?php $postParams = $block->getAddToCartPostParams($_item); ?>
																<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
																	<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
																	<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
																	<?php echo $block->getBlockHtml('formkey')?>
																	<button type="submit"
                                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																			class="action tocart primary grid"
                                                                            >
																		<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																	</button>
																</form>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                                <?php if ($showWishlist || $showCompare): ?>
                                                    <div class="actions-secondary" data-role="add-to-links">
                                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                            <a href="#"
                                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                               class="action towishlist" data-action="add-to-wishlist"
                                                               title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                            <a href="#" class="action tocompare"
                                                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                               title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </ul>
                    </div>
                </div>
            <!--</div>
        </div>
    </section>-->
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
        }
    }
    </script>
<?php endif;?>
