<?php
    $_helper = $this->helper('FlixMedia\Js\Helper\Data');
    $_product = $_helper->getProduct();
    $_config = $_helper->getConfigParams();
    var_dump($_config);
?>
<div data-mage-init='
{"data": 
{
    "mpn": "<?= $_product->getMpn() ?>",
    "sku": "<?= $_product->getSku() ?>",
    "brand": "Samsung",
    "distributor": "9040",
    "language":"cr"
}}'>
    <div id="flix-inpage"></div>
    <div id="flix-minisite" style="display:none"></div>
</div>