<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<form class="form contact col-md-6 col-md-offset-3"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
        <div class="field note no-label"><?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?></div>
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('First name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('First name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
		<div class="field lastname required">
            <label class="label" for="lastname"><span><?= $block->escapeHtml(__('Last name')) ?></span></label>
            <div class="control">
                <input name="lastname" id="lastname" title="<?= $block->escapeHtmlAttr(__('Last name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('lastname') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field address1 required">
            <label class="label" for="address1"><span><?= $block->escapeHtml(__('Address')) ?></span></label>
            <div class="control">
                <input name="address1" id="address1" title="<?= $block->escapeHtmlAttr(__('Address')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('address1')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
		<div class="field address2">
            <label class="label" for="address2"><span><?= $block->escapeHtml(__('Address')) ?></span></label>
            <div class="control">
                <input name="address2" id="address2" title="<?= $block->escapeHtmlAttr(__('Address')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('address2')) ?>" class="input-text" type="text" />
            </div>
        </div>
		<div class="field city required">
            <label class="label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
            <div class="control">
                <input name="city" id="city" title="<?= $block->escapeHtmlAttr(__('City')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('city')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
		<div class="field state required">
            <label class="label" for="state"><span><?= $block->escapeHtml(__('State')) ?></span></label>
            <div class="control">
                <input name="state" id="state" title="<?= $block->escapeHtmlAttr(__('State')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('state')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
		<div class="field zip required">
            <label class="label" for="zip"><span><?= $block->escapeHtml(__('Zip')) ?></span></label>
            <div class="control">
                <input name="zip" id="zip" title="<?= $block->escapeHtmlAttr(__('zip')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('zip')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
		<div class="field country required">
            <label class="label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
            <div class="control">
                <input name="country" id="country" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('country')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
		<div class="field telephone required">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
		<div class="field product">
            <label class="label" for="product"><span><?= $block->escapeHtml(__('Product or model')) ?></span></label>
            <div class="control">
                <input name="product" id="product" title="<?= $block->escapeHtmlAttr(__('Product or model')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('product')) ?>" class="input-text" type="text" />
            </div>
        </div>
		<div class="field note">
            <label class="label" for="note"><span><?= $block->escapeHtml(__('Note')) ?></span></label>
            <div class="control">
                <div class="form-note">
					<p>
						<b><?php echo __('Note:')?></b> <?php echo __('For all product-related questions, please include your Model Number or specific product name so that we can help you better.')?>
					</p>
				</div>
            </div>
        </div>
		<div class="field comment required">
            <label class="label" for="comment"><span><?= $block->escapeHtml(__('Comment')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Comment')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment'))?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
