<?php if($this->getTitle()=="Error"){ ?>
    <p><?php echo __('Se ha producido un error por favor contacte al administrador del sitio') ?></p>
<?php } else{ ?>
<h1><?php echo $this->getTitle() ?></h1>
<table>
    <tr>
        <td>Orden #</td>
        <td><?php echo $this->getReference() ?></td>
    </tr>
    <tr>
        <td>Valor</td>
        <td><?php echo $this->getAmount() ?></td>
    </tr>
    <tr>
        <td>Método de pago</td>
        <td><?php echo $this->getPaymentMethod() ?></td>
    </tr>
    <tr>
        <td>Estado</td>
        <td><?php echo $this->getResponse() ?></td>
    </tr>
</table>
<?php } ?>