<?php if($this->getTitle()=="Error"){ ?>
    <p><?php echo __('Se ha producido un error por favor contacte al administrador del sitio') ?></p>
<?php } else{ ?>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="page-title-wrapper">
                <h1 class="page-title"><?php echo $this->getTitle() ?></h1>
            </div>
            <table class="col-xs-12 col-md-8 col-md-offset-2 payment-result">
                <tr>
                    <td><b>Orden #</b></td>
                    <td><?php echo $this->getReference() ?></td>
                </tr>
                <tr>
                    <td><b>Valor</b></td>
                    <td><?php echo $this->getAmount() ?></td>
                </tr>
                <tr>
                    <td><b>Método de pago</b></td>
                    <td><?php echo $this->getPaymentMethod() ?></td>
                </tr>
                <tr>
                    <td><b>Estado</b></td>
                    <td><?php echo $this->getResponse() ?></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <a href="<?php echo $this->getBaseUrl() ?>" class="action primary"><span><?php echo __('Back to home')?></span></a>
        </div>
    </div>
</div>
<?php } ?>