<?php if($this->getTitle()=="Error"){ ?>
    <p><?php echo __('Se ha producido un error por favor contacte al administrador del sitio') ?></p>
<?php } else{ ?>
<div class="container">
    <div class="row">
        <div class="col-xs-12 payment-result">
            <div class="page-title-wrapper">
                <h1 class="page-title"><?php echo $this->getTitle() ?></h1>
            </div>
            <table class="col-xs-12 col-md-8 col-md-offset-2">
                <tr>
                    <td><b>Order #</b></td>
                    <td><?php echo $this->getReference() ?></td>
                </tr>
                <tr>
                    <td><b>Valor</b></td>
                    <td><?php echo $this->getAmount() ?></td>
                </tr>
                <tr>
                    <td><b>Método de pago</b></td>
                    <td><?php echo $this->getPaymentMethod() ?></td>
                </tr>
                <?php if($this->getResponse() != ''){ ?>
                    <tr>
                        <td><b>Estado</b></td>
                        <td><?php echo $this->getResponse() ?></td>
                    </tr>
                <?php } ?>
            </table>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="/" class="action primary"><span><?php echo __('Back to home')?></span></a>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
/* XCB GTM */
/*
foreach ($block as $_product){
    $producto = "{
        'id': '{$block->getSku()}',
        'name': '{$_product->getName()}',
        'price': '{$_product->getFinalPrice()}',
        'brand': 'HOM',
        'category': '{$_product->getName()}',
        'variant': 'productVariant',
        'quantity': {$_product->getQty()},
        'coupon': ''
    }";
    $gtm_prods = !empty($gtm_prods)? $gtm_prods.','.$producto : $producto;
}
*/
$lid            = $this->getReference();
echo '<hr>';
print_r($lid);
die('<hr>');
$objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
$order          = $objectManager->create('Magento\Sales\Model\Order')->load($lid);
$items          = $order->getAllItems();
foreach ($items as $i)
{
    $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($i->getProductId());
    $producto = "{

        'id': '{$_product->getSku()}',
        'name': '{$_product->getName()}',
        'price': '{$_product->getFinalPrice()}',
        'brand': 'HOM',
        'category': '{$_product->getName()}',
        'variant': 'productVariant',
        'quantity': {$_product->getQty()},
        'coupon': ''
        
    }";
    $gtm_prods = !empty($gtm_prods)? $gtm_prods.','.$producto : $producto;
}
$final_price = $this->getAmount();
$order = $this->getReference();
echo <<<JG
<script type="text/javascript">
    setTimeout(function(){
    dataLayer.push({
        'event': 'transaction',
        'ecommerce': {
            'purchase': {
                'actionField': {
                    'id': {$order},
                    'affiliation': 'HOM',
                    'revenue': {$final_price},
                    'tax': 'orderTax',
                    'shipping': 'orderShipping',
                    'coupon': 'orderCoupon'
                },
                'products': [{$gtm_prods}]
            }
        }
    });
},3000);
</script>
JG;
/* XCB END */
?>
<?php } ?>