<?php if($this->getTitle()=="Error"){ ?>
    <p><?php echo __('Se ha producido un error por favor contacte al administrador del sitio') ?></p>
<?php } else{ ?>
<div class="container">
    <div class="row">
        <div class="col-xs-12 payment-result">
            <div class="page-title-wrapper">
                <h1 class="page-title"><?php echo $this->getTitle() ?></h1>
            </div>
            <table class="col-xs-12 col-md-8 col-md-offset-2">
                <tr>
                    <td><b>Order #</b></td>
                    <td><?php echo $this->getReference() ?></td>
                </tr>
                <tr>
                    <td><b>Valor</b></td>
                    <td><?php echo $this->getAmount() ?></td>
                </tr>
                <tr>
                    <td><b>Método de pago</b></td>
                    <td><?php echo $this->getPaymentMethod() ?></td>
                </tr>
                <?php if($this->getResponse() != ''){ ?>
                    <tr>
                        <td><b>Estado</b></td>
                        <td><?php echo $this->getResponse() ?></td>
                    </tr>
                <?php } ?>
            </table>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="/" class="action primary"><span><?php echo __('Back to home')?></span></a>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
/* XCB GTM */
$lid            = $this->getReference();
$objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
$order          = $objectManager->create('Magento\Sales\Model\Order');
$orderInfo      = $order->loadByIncrementId($lid);
echo '<pre>';

echo '<hr>';
$temp = $this->itemFactory->create()->getCollection()->addFieldToFilter('order_id', $lid);
foreach($temp as $a){
    print_r(get_class_methods($a));
}
die;
print_r(get_class_methods($order));

#print_r($order->getBaseDiscountTaxCompensationAmount());
#print_r($order->getBaseDiscountTaxCompensationInvoiced());
#print_r($order->getBaseDiscountTaxCompensationRefunded());
print_r($order->getBaseShippingDiscountTaxCompensationAmnt());
#print_r($order->getBaseShippingInclTax());
#print_r($order->getBaseShippingTaxAmount());
#print_r($order->getBaseShippingTaxRefunded());
#print_r($order->getBaseSubtotalInclTax());
#print_r($order->getBaseTaxAmount());
#print_r($order->getBaseTaxCanceled());
#print_r($order->getBaseTaxInvoiced());
#print_r($order->getBaseTaxRefunded());
#print_r($order->getCustomerTaxvat());
#print_r($order->getDiscountTaxCompensationAmount());
#print_r($order->getDiscountTaxCompensationInvoiced());
#print_r($order->getDiscountTaxCompensationRefunded());
#print_r($order->getShippingDiscountTaxCompensationAmount());
#print_r($order->getShippingInclTax());
#print_r($order->getShippingTaxAmount());
#print_r($order->getShippingTaxRefunded());
#print_r($order->getSubtotalInclTax());
#print_r($order->getSubtotalInclTax());*/
/*
foreach(get_class_methods($order) as $metod){
    echo '<hr>';
    if ($metod != '__construct'){
        echo ('<p>'.$metod.'</p>');
        print_r($_product->$metod());
    }
    echo '<hr>';
}
*/
echo '</pre>';
die;
$items          = $orderInfo->getAllItems();

foreach ($items as $i)
{
    $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($i->getProductId());
    $producto = "{
        'id': '{$_product->getSku()}',
        'name': '{$_product->getName()}',
        'price': '{$_product->getFinalPrice()}',
        'brand': 'HOM',
        'category': '{$_product->getName()}',
        'variant': 'productVariant',
        'quantity': {$_product->getQty()},
        'coupon': ''
        
    }";
    $gtm_prods = !empty($gtm_prods)? $gtm_prods.','.$producto : $producto;
}
$final_price = $this->getAmount();
$tax = $order->getTaxAmount();
$shipping = $order->getShippingAmount();
$coupon = $order->getCouponCode();
$order = $this->getReference();
echo <<<JG
<script type="text/javascript">
    setTimeout(function(){
    dataLayer.push({
        'event': 'transaction',
        'ecommerce': {
            'purchase': {
                'actionField': {
                    'id': {$order},
                    'affiliation': 'HOM',
                    'revenue': {$final_price},
                    'tax': {$tax},
                    'shipping': {$shipping},
                    'coupon': '{$coupon}'
                },
                'products': [{$gtm_prods}]
            }
        }
    });
},3000);
</script>
JG;
/* XCB END */
?>
<?php } ?>