<?php 
$_helper = $this->helper('Magento\Catalog\Helper\Output'); 
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$_product = $block->getProduct(); 
$atts = $_product->getProductAttributes();
$fields = array();
if($atts){
	$fields = $_helperCdi->getAttributeArrayFromJson($atts);
}
?>
<?php if(count($fields)){ ?>
	<section class="product-specs fullwidth dkgryBG" id="product-specs">
		<div class="container">
			<h3><?php echo __('What You Get')?></h3>
			<div class="row">
				<ul class="feature-icons">
				<?php foreach($fields as $field){ ?>
					<li class="col-md-6">
						<img src="<?php echo $this->getViewFileUrl("images/attributes/{$field['image']}"); ?>" alt="<?php echo (isset($field['$field'])) ? $field['$field'] : '';?>" />
						<?php if(isset($field['title']) || isset($field['desc'])){ ?>
							<div class="callout-text">
								<?php if(isset($field['title'])){ ?>
									<b><?php echo $field['title'];?></b>
								<?php } ?>
								<?php if(isset($field['desc'])){ ?>
									<p><?php echo $field['desc'];?></p>
								<?php } ?>
							</div>
						<?php } ?>
					</li>
				<?php } ?>
				</ul>
			</div>
		</div>
	</section>
<?php } ?>