<?php $_product = $block->getProduct(); 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
echo $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId());
?>
<h1 class="product-name"><?= $block->escapeHtml($_product->getName()) ?></h1>
<div class="sku">
	<span class="label"><?php echo __('SKU:')?></span>
	<span class="value"><?= $block->escapeHtml($_product->getSku()) ?></span>
</div>
<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
<div class="short-description">
<p><?php echo $_product->getShortDescription() ?></p>
</div>