<?php 
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
$_helper = $this->helper('Magento\Catalog\Helper\Output'); 
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$_product = $block->getProduct(); 
$atts = $_product->getProductAttributes();
$fields = array();
if($atts){
	$fields = $_helperCdi->getAttributeArrayFromJson($atts);
}
?>
<section class="product-specs fullwidth" style="background: #F6F6F6;" id="product-specs">
	<h3><?php echo __('Quick Specs')?></h3>
	<div class="container">
		<div class="row">
			<?php if($image = $_helperCdi->getCustomProductImage($_product, 'specs_img1')){ ?>
				<?php $productImage1 = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'specs_img1')->setImageFile($image);?>
				<div class="col-sm-9 col-12">
					<img src="<?php echo $productImage1->getUrl() ?>" alt="<?php echo $_product->getName() ?>" />
				</div>
			<?php } ?>
			<div class="col-sm-3 col-12" style="text-align: center;">
				<b><?php echo __('Dimensions')?></b>
				<ul>
					<?php if($_product->getTsDimensionsHeight()): ?>
						<li><?php echo $_product->getResource()->getAttribute('height')->getStoreLabel();?>: <?= $_product->getTsDimensionsHeight() ?></li>
					<?php endif;?>
					<?php if($_product->getTsDimensionsWidth()): ?>
						<li><?php echo $_product->getResource()->getAttribute('width')->getStoreLabel();?>: <?= $_product->getTsDimensionsWidth() ?></li>
					<?php endif;?>
					<?php if($_product->getTsDimensionsLength()): ?>
						<li><?php echo $_product->getResource()->getAttribute('ts_dimensions_length')->getStoreLabel();?>: <?= $_product->getTsDimensionsLength() ?></li>
					<?php endif;?>
					<?php if($_product->getDepth()): ?>
						<li><?php echo $_product->getResource()->getAttribute('depth')->getStoreLabel();?>: <?= $_product->getDepth() ?></li>
					<?php endif;?>
					<?php if($_product->getWeight()): ?>
						<li><?php echo $_product->getResource()->getAttribute('weight')->getStoreLabel();?>: <?= number_format((float)$_product->getWeight(), 2, '.', ''); ?> <?php echo $_helperCdi->getWeightUnit(); ?></li>
					<?php endif;?>
				</ul>
			</div>
		</div>
		<?php if(count($fields)){ ?>
			<?php $colsm = $_helperCdi->getColumnsBt(count($fields));?>
			<div class="row">
				<ul class="feature-icons">
				<?php foreach($fields as $field){ ?>
					<li>
						<img src="<?php echo $this->getViewFileUrl("images/attributes/{$field['image']}"); ?>" alt="<?php echo (isset($field['$field'])) ? $field['$field'] : '';?>" />
						<?php if(isset($field['title']) || isset($field['desc'])){ ?>
							<div class="callout-text">
								<?php if(isset($field['title'])){ ?>
									<b><?php echo $field['title'];?></b>
								<?php } ?>
								<?php if(isset($field['desc'])){ ?>
									<p><?php echo $field['desc'];?></p>
								<?php } ?>
							</div>
						<?php } ?>
					</li>
				<?php } ?>
				</ul>
			</div>
		<?php } ?>
	</div>
</section>