<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>
<?php
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$cartEnabled = $_helperCdi->getStoreConfig('general/store_information/custom_disable_checkout');
?>
<div class="fullwidth">
	<div class="container">
		
			<div class="col-sm-4 col-12">
				<div class="sticky-name">
					<?= $block->escapeHtml($_product->getName()) ?>
				</div>
			</div>
			<div class="col-sm-4 col-12" style="text-align: center;">
				<ul class="sticky-sections">
					<li class="goto-section"><a href="#features"><?php echo __('Features')?></a></li>
					<li class="goto-section"><a href="#product-specs"><?php echo __('Specs')?></a></li>
					<li class="goto-section"><a href="#product-in-box"><?php echo __('In the Box')?></a></li>
				</ul>
			</div>
			<div class="col-sm-4 col-12">
				<?php if($cartEnabled){ ?>
					<div class="sticky-price-box">
						<div class="sticky-price">
							<?php //$block->getChildHtml('product.price.final') ?>
						</div>
						<div class="sticky-addto">
							<button class="button btn-cart">
								<span><span><a href="#features"> + </a></span></span>
							</button>
						</div>
					</div>
				<?php } ?>
			</div>
		</div>
	
</div>
<script>
    require(['jquery'], function($){
		//en este js cargar las opciones del sticky-sections
        //console.log('product page js ');
		$(".sticky-sections li a, .sticky-addto a").click(function(e){
			e.preventDefault();
			var href = $(this).attr('href');
			if('#features' != href){
				element = $(href);
			}else{
				element = $('.product-essential').next();
			}
			stick = $('.sticky-product-nav').outerHeight();
			$('html,body').animate({
				scrollTop: element.offset().top - stick
			}, 'slow');
			
		});
    });
</script>