<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_cdiHelper = $this->helper('Cdi\Custom\Helper\Api');?>
<div class="actions">
    <?php  
    $_order = $block->getOrder();
    $iwsOrder = $_cdiHelper->getIwsOrderBy('order_id', $_order->getEntityId(), false, false);
    ?>
    <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
        <a href="#" data-post='<?php /* @escapeNotVerified */ echo
        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
            ->getPostData($block->getReorderUrl($_order))
        ?>' class="action order">
            <span><?= /* @escapeNotVerified */ __('Reorder') ?></span>
        </a>
    <?php endif ?>
    <a class="action print"
       href="<?= /* @escapeNotVerified */ $block->getPrintUrl($_order) ?>"
       onclick="this.target='_blank';">
        <span><?= /* @escapeNotVerified */ __('Print Order') ?></span>
    </a>
    <?php if($iwsOrder && $iwsOrder->getId()):?>
        <?php $guideData = unserialize($iwsOrder->getMienvioUploadResp());?>
        <?php if(is_array($guideData) && !empty($guideData)):?>
            <a class="action tracking"
            href="<?php echo $this->getUrl('mienvio/shipment/status/order_id/'.$_order->getId()) ?>"
            >
                <span><?= /* @escapeNotVerified */ __('Tracking') ?></span>
            </a>
        <?php endif;?>

        <?php $invoiceData = unserialize($iwsOrder->getTraxInvoice());?>
        <?php if(is_array($invoiceData) && !empty($invoiceData)):?>
            <a class="action tracking"
            href="<?php echo $this->getUrl('taxid/invoice/status/order_id/'.$_order->getId()) ?>"
            >
                <span><?= /* @escapeNotVerified */ __('Invoice') ?></span>
            </a>
        <?php endif;?>
    <?php endif;?>
    <?= $block->getChildHtml() ?>
</div>
