<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$cartEnabled = (bool) $_helperCdi->getStoreConfig('general/store_information/custom_disable_checkout');
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable() && $cartEnabled): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Quantity') ?></span></label>
            <div class="control">
              <div class="control-qty remove disable">
                <span>-</span>
              </div>
              <input type="number"
                     name="qty"
                     id="qty"
                     value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                     title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                     class="input-text qty"
                     data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                     />
              <div class="control-qty add">
                <span>+</span>
              </div>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
            /* XCB */
            dataLayer.push({
            'event': 'addToCart',
            'ecommerce': {
                'currencyCode': '',
                'add': {
                    'products': [{
                        'name': <?php  echo $_product->getName(); ?>,
                        'id': <?php echo $_product->getProduct()->getId(); ?>,
                        'price': <?php echo $block->getProductPrice($_product); ?>,
                        'brand': '',
                        'category': '',
                        'variant': '',
                        'quantity': <?php echo $block->getProductDefaultQty() * 1 ?>
                    }]
                }
            }
        });
        /* XCB FIN */
        }
    }
</script>
