<?php
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $block->getCurrentCategory();
	$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
	$atts = $_category->getCatAttributes();
	$fields = array();
	if($atts){
		$fields = $_helperCdi->getAttributeArrayFromJson($atts);
	}
?>
<?php if(count($fields)){ ?>
	<?php $colsm = $_helperCdi->getColumnsBt(count($fields));?>
	<section class="category-features">
		<div class="container">
			<div class="row">
				<?php foreach($fields as $field){ ?>
					<div class="col-md-<?php echo $colsm?> col-xs-6 feature-callout">
						<img src="<?php echo $this->getViewFileUrl("images/{$field['image']}"); ?>" alt="<?php echo (isset($field['$field'])) ? $field['$field'] : '';?>" />
						<?php if(isset($field['title']) || isset($field['desc'])){ ?>
							<div class="callout-text">
								<?php if(isset($field['title'])){ ?>
									<b><?php echo $field['title'];?></b><br>
								<?php } ?>
								<?php if(isset($field['desc'])){ ?>
									<p><?php echo $field['desc'];?></p>
								<?php } ?>
							</div>
						<?php } ?>
					</div>
				<?php } ?>
			</div>
		</div>
	</section>
<?php } ?>