<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $block->getCurrentCategory();
	$subCats = $_category->getChildrenCategories();
    $gtm_prods =''; # GTM variable
    $posicion = 1; # GTM variable
?>
<?php if(count($subCats)){ ?>
<?php $cols = 12/count($subCats); ?>
	<section class="category-products">
		<div class="container">
			<div class="row">
				<?php
				foreach ($subCats as $subcat) {
					$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
					$prods = $block->getCategoryProducts($_category);
					$subcaturl = $subcat->getUrl();
					$_imgHtml = '';
					if ($_imgUrl = $_category->getImageUrl()) {
						$_imgHtml = "<img src='{$_imgUrl}' usemap='#chill-map-{$subcat->getId()}'/>";
						$_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
					} ?>			
					<div class="col-sm-<?php echo $cols;?> col-12 category-callout">
						<?php echo $_imgHtml;?>
						<map name="chill-map-<?php echo $subcat->getId(); ?>">
							<?php foreach($prods as $prod){ ?>
								<?php 
								$coords = explode(',', $prod->getMapImageLink());
								$cType = (count($coords) == 4) ? 'rect' : 'poly';
                                
                                /* XCB GTM */
                                $foo = $prod;
                                $producto = "{        
                                    'name': '{$prod->getName()}',
                                    'id': '{$prod->getSku()}',
                                    'price': '{$prod->getFinalPrice()}',
                                    'brand': 'JAM',
                                    'category': '{$prod->getCategory()}',
                                    'variant': 'productVariant',
                                    'list': '{$subcat->getName()}',
                                    'position': ".$posicion++."
                                }";
                                $gtm_prods = !empty($gtm_prods)? $gtm_prods.','.$producto : $producto;
                                /* XCB END */
								?>
								<area 
									href="<?php echo $prod->getProductUrl()?>" 
									alt="<?php echo $prod->getName()?>" 
									coords="<?php echo $prod->getMapImageLink()?>" 
									shape="<?php echo $cType; ?>" 
								/>
							<?php }  ?>
						</map>
						<h2><?php echo $subcat->getName(); ?></h2>
						<ul class="cat-product-links">
							<?php foreach($prods as $prod){ ?>
								<li><a href="<?php echo $prod->getProductUrl()?>"><nobr><?php echo $prod->getName()?></nobr></a></li>
							<?php }  ?>
						</ul>
					</div>
				<?php } ?>
			</div>
		</div>
	</section>
<?php } 
?>