<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $block->getCurrentCategory();
	$subCats = $_category->getChildrenCategories();
?>
<section class="fullwidth category-products">
	<div class="content">
		<?php
		foreach ($subCats as $subcat) {
			$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
			$prods = $block->getCategoryProducts($_category);
			$subcaturl = $subcat->getUrl();
			$_imgHtml = '';
			if ($_imgUrl = $_category->getImageUrl()) {
				$_imgHtml = "<img src='{$_imgUrl}' usemap='#chill-map-{$subcat->getId()}'/>";
				$_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
			} ?>			
			<div class="cms-col-1-2 mobile-cms-col-1-1 category-callout">
				<?php echo $_imgHtml;?>
				<map name="chill-map-<?php echo $subcat->getId(); ?>">
					<?php foreach($prods as $prod){ ?>
						<area href="<?php echo $prod->getProductUrl()?>" alt="<?php echo $prod->getName()?>" coords="<?php echo $prod->getUrlMapImageLink()?>" shape="rect" />
					<?php }  ?>
				</map>
				<h2><?php echo $subcat->getName(); ?></h2>
				<ul class="cat-product-links">
					<?php foreach($prods as $prod){ ?>
						<li><a href="<?php echo $prod->getProductUrl()?>"><nobr><?php echo $prod->getName()?></nobr></a></li>
					<?php }  ?>
				</ul>
			</div>
		<?php } ?>
	</div>
</section>