<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/*print_r(get_class_methods($block));
print_r($block->getLoadedProductCollection());
die('succes');*/
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">        
                <?php if ($block->getOrderId()):?>
                    <?php if ($block->getCanViewOrder()) :?>
                        <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
                    <?php  else :?>
                        <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
                    <?php endif;?>
                        <p><?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
                <?php endif;?>

                <?= $block->getAdditionalInfoHtml() ?>

                <div class="actions-toolbar">
                    <div class="primary">
                        <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
/*    $order = $block->escapeHtml($block->getOrderId());
echo <<<JG
<script>
    "dataLayer.push({
        'event': 'transaction',
        'ecommerce': {
            'purchase': {
                'actionField': {
                    'id': {$order},
                    'affiliation': HOM,
                    'revenue': orderTotal,
                    'tax': orderTax,
                    'shipping': orderShipping,
                    'coupon': orderCoupon
                },
                'products': [{
                    'id': productSku,
                    'name': productName,
                    'price': productPrice,
                    'brand': productName,
                    'category': productCategory,
                    'variant': productVarian,
                    'quantity': productQty,
                    'coupon': productCoupon
                },
                {
                    'id': 'MM101HOM24',
                    'name': 'NO BOUNDS XL SIGNATURE GREY', 
                    'price': '3959',
                    'brand': 'MARLEY', 
                    'category': 'PARLANTES',
                    'variant': 'BLANCO',
                    'quantity': 2,
                    'coupon': 'AEIOU'
                }]
            }
        }
    });
</script>
JG;*/
?>