<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">        
                <?php if ($block->getOrderId()):?>
                    <?php if ($block->getCanViewOrder()) :?>
                        <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
                    <?php  else :?>
                        <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
                    <?php endif;?>
                        <p><?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
                <?php endif;?>

                <?= $block->getAdditionalInfoHtml() ?>

                <div class="actions-toolbar">
                    <div class="primary">
                        <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
/* XCB GTM */
$_productCollection = $block->getLoadedProductCollection();
$final_price = $block->getFinalPrice();
$qty = $_productCollection->count();
foreach ($_productCollection as $_product){
    $producto = "{
        'id': '{$_productCollection->getSku()}',
        'name': '{$_product->getName()}',
        'price': '{$_product->getFinalPrice()}',
        'brand': 'HOM',
        'category': '{$_product->getName()}',
        'variant': 'productVariant',
        'quantity': {$_product->getQty()},
        'coupon': ''
    }";
    $gtm_prods = !empty($gtm_prods)? $gtm_prods.','.$producto : $producto;
}
$order = $block->getOrderId();
echo <<<JG
<script>
    alert("finaliza");
    $('document').ready(function(){
    "dataLayer.push({
        'event': 'transaction',
        'ecommerce': {
            'purchase': {
                'actionField': {
                    'id': {$order},
                    'affiliation': 'HOM',
                    'revenue': {$final_price},
                    'tax': 'orderTax',
                    'shipping': 'orderShipping',
                    'coupon': 'orderCoupon'
                },
                'products': [{$gtm_prods}]
            }
        }
    });
});
    dataLayer.push({'event':'ga_event','category':'Carrito de compras','action':'Label','label':'Continuar Comprando'});
</script>
JG;
/* XCB END */
?>