<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$count = 0;
?>
<?php if (!$_productCollection->count()): ?>
    <div class="container">
        <div class="message info empty text-center"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
    <style>
        .price-box{
            display: block !important;
            font-weight: 300;
        }
    </style>
        <ul class="products list items product-items" id="container-grid">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product col-sm-6 col-md-3 col-xl-3" style="opacity: 1;">
				<div class="product-image-wrapper">
					<?php
					$baseImage = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'category_page_grid');//->getUrl();
					$productImage = $block->getImage($_product, $imageDisplayArea);
					if ($pos != null) {
						$position = ' style="left:' . $productImage->getWidth() . 'px;'
							. 'top:' . $productImage->getHeight() . 'px;"';
					}
					?>
                    
					<?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo product-image" tabindex="-1">
                        <img src="<?php echo $baseImage->getUrl() ?>" alt="<?php echo $_product->getName() ?>" />
                    </a>
				</div>
				<h2 class="product-name">
					<a class=""
					   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
						<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
					</a>
				</h2>
				<div class="atributo-familia">
				    <?php $type = $_helper->productAttribute($_product, $_product->getMarleyType(), 'marley_type');?>
					<?php echo ($type !== 'No') ? $type : '';  ?>
				</div>
                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                <div class="actions">
                    <?php if ($_product->isSaleable()): ?>
                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                            <?php echo $block->getBlockHtml('formkey')?>
                            <button type="submit"
                                title="<?php echo $block->escapeHtml(__('Buy')); ?>"
                                class="button btn-cart">
                                <span style="display: block; font-size: 20px; font-weight: 600;"><?php /* @escapeNotVerified */ echo __('Buy') ?></span>
                            </button>
                        </form>
                    <?php else: ?>
                        <a class="button btn-cart"
                        href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                            <span>
                            <?= /* @escapeNotVerified */ __('View more') ?>
                            </span>
                        </a>
                    <?php endif; ?>
				</div>
            </li>
            <?php endforeach; ?>
        </ul>        
    </div>
    <?php if ($block->getPagerHtml()): ?>
	    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
        <style type="text/css">
            .custom-pager .limiter{
                display: block !important;
            }
        </style>
	<?php endif ?>

    <?php echo $block->getToolbarHtml() ?>
    
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>