<?php 
$banner = $this->getBanner(); 
$color = ($banner->getFontColor() != '') ? $banner->getFontColor() : '#ffffff';
$bannerClass = $banner->getBannerClass();
$isFullWidth = false;
if($bannerClass){
	$isFullWidth = strpos($bannerClass, 'fullwidth');
	$isFullWidth = ($isFullWidth !== false);
}
?>
<section 
	id="banner-image-<?php echo $banner->getId();?>" 
	class="<?php echo $banner->getBannerClass();?>" 
	<?php if($isFullWidth && $banner->getImage()){ ?>
		style="background: url('<?php echo $this->getBannerImageUrl($banner);?>') no-repeat center center transparent; background-size: cover;"
	<?php } ?>
>
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-12">
				<?php if($banner->getClickUrl()){ ?>
					<a href="<?php echo $banner->getClickUrl()?>" target="<?php echo $this->getTargetValue()?>">
				<?php } ?>
					<div class="text-block-banner">
						<?php if($banner->getTitle() || $banner->getCaption()){ ?>
							<div class="text-overlay-banner banner-text-<?php echo $banner->getTextLocation(); ?>" style="color: <?php echo $color;?>">
								<?php if($banner->getTitle()){ ?>
									<h1 class="caption-title"><?php echo $banner->getTitle();?></h1>
								<?php } ?>
								<?php if($banner->getCaption()){ ?>
									<div class="caption-desc"><?php echo $banner->getCaption();?></div>
								<?php } ?>
							</div>
						<?php } ?>
						<?php if(!$isFullWidth && $banner->getImage()){ ?>
							<img src="<?php echo $this->getBannerImageUrl($banner);?>" alt="<?php echo $banner->getImageAlt()?>" />
						<?php } ?>
					</div>
				<?php if($banner->getClickUrl()){ ?>
					</a>
				<?php } ?>
			</div>
		</div>
	</div>
</section>
<?php if($banner->getBannerCss()){ ?>
	<style><?php echo $this->cleanCss($banner->getBannerCss()) ?></style>
<?php } ?>