<?php 
$banner = $this->getBanner(); 
$color = ($banner->getFontColor() != '') ? $banner->getFontColor() : '#ffffff';
$bannerClass = $banner->getBannerClass();
$isFullWidth = false;
if($bannerClass){
	$isFullWidth = strpos($bannerClass, 'fullwidth');
	$isFullWidth = ($isFullWidth !== false);
}
?>
<section 
	id="banner-image-<?php echo $banner->getId();?>" 
	class="<?php echo $banner->getBannerClass();?>" 
	<?php if($isFullWidth && $banner->getImage()){ ?>
		<?php 
			$image = $this->getBannerImageUrl($banner); // imagen desktop
			$respImage = ($banner->getImageresp()) ? $this->getBannerImageUrl($banner, 'responsive') : $image; //imagen mobile
		?>
		style="background: url('<?php echo $image;?>') no-repeat center center transparent; background-size: cover;"
	<?php } ?>
>
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-12">
				<?php if($banner->getClickUrl()){ ?>
					<a href="<?php echo $banner->getClickUrl()?>" target="<?php echo $this->getTargetValue()?>">
				<?php } ?>
					<div class="text-block-banner">
						<?php if($banner->getTitle() || $banner->getCaption()){ ?>
							<div class="text-overlay-banner banner-text-<?php echo $banner->getTextLocation(); ?>" style="color: <?php echo $color;?>">
								<?php if($banner->getTitle()){ ?>
									<h1 class="caption-title"><?php echo $banner->getTitle();?></h1>
								<?php } ?>
								<?php if($banner->getCaption()){ ?>
									<div class="caption-desc"><?php echo $banner->getCaption();?></div>
								<?php } ?>
							</div>
						<?php } ?>
						<?php if(!$isFullWidth && $banner->getImage()){ ?>
							<picture>
								<?php 
								$image = $this->getBannerImageUrl($banner); // imagen desktop
								$respImage = ($banner->getImageresp()) ? $this->getBannerImageUrl($banner, 'responsive') : $image; //imagen mobile
								?>
								<source media="(max-width: 650px)" srcset="<?php echo $respImage;?>">
								<img src="<?php echo $image;?>" alt="<?php echo $banner->getImageAlt()?>" />
							</picture>
						<?php } ?>
					</div>
				<?php if($banner->getClickUrl()){ ?>
					</a>
				<?php } ?>
			</div>
		</div>
	</div>
</section>
<?php if($banner->getBannerCss()){ ?>
	<style><?php echo $this->cleanCss($banner->getBannerCss()) ?></style>
<?php } ?>