<?php 
$banner = $this->getBanner(); 
$color = ($banner->getFontColor() != '') ? $banner->getFontColor() : '#ffffff';
$bannerClass = $banner->getBannerClass();
$isFullWidth = false;
if($bannerClass){
	$isFullWidth = strpos($bannerClass, 'fullwidth');
	$isFullWidth = ($isFullWidth !== false);
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
?>
<section id="banner-image-<?php echo $banner->getId();?>" class="<?php echo $banner->getBannerClass();?> <?php echo ($isFullWidth) ? 'banner-background' : '';?>">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-12">
				<?php if($banner->getClickUrl() && !$banner->getButtontext()){ ?>
					<a href="<?php echo $banner->getClickUrl()?>" target="<?php echo $this->getTargetValue()?>">
				<?php } ?>
					<div class="text-block-banner">
						<?php if(!$isFullWidth && $banner->getImage()){ ?>
							<picture>
								<?php 
								$image = $this->getBannerImageUrl($banner); // imagen desktop
								$respImage = ($banner->getImageresp()) ? $this->getBannerImageUrl($banner, 'responsive') : $image; //imagen mobile
								?>
								<source media="(max-width: 650px)" srcset="<?php echo $respImage;?>">
								<img src="<?php echo $image;?>" alt="<?php echo $banner->getImageAlt()?>" />
							</picture>
						<?php } ?>
						<?php if($banner->getTitle() || $banner->getCaption() || $banner->getButtontext()){ ?>
							<div 
								class="text-overlay-banner banner-text-<?php echo $banner->getTextLocation(); ?> banner-text-vertical-<?php echo ($banner->getTextLocationV()) ? $banner->getTextLocationV() : 'middle'; ?>" 
								style="color: <?php echo $color;?>"
							>
								<?php if($banner->getTitle()){ ?>
									<h1 class="caption-title"><?php echo $banner->getTitle();?></h1>
								<?php } ?>
								<?php if($banner->getCaption()){ ?>
									<div class="caption-desc">
									desc
										<?php echo $objectManager->get('\Magento\Cms\Model\Template\FilterProvider')->getBlockFilter()->filter($banner->getCaption());?>
									</div>
								<?php } ?>
								<?php if($banner->getButtontext()){ ?>
									<a class="banner-button" href="<?php echo $banner->getClickUrl(); ?>" target="<?php echo $this->getTargetValue()?>">
										<?php echo $banner->getButtontext();?>
									</a>
								<?php } ?>
							</div>
						<?php } ?>
					</div>
				<?php if($banner->getClickUrl() && !$banner->getButtontext()){ ?>
					</a>
				<?php } ?>
			</div>
		</div>
	</div>
</section>
<?php if($banner->getBannerCss()){ ?><style><?php echo $this->cleanCss($banner->getBannerCss()) ?></style><?php } ?>
<?php if($isFullWidth && $banner->getImage()){ ?>
	<?php 
		$image = $this->getBannerImageUrl($banner); // imagen desktop
		$respImage = ($banner->getImageresp()) ? $this->getBannerImageUrl($banner, 'responsive') : $image; //imagen mobile
	?>
	<style>#banner-image-<?php echo $banner->getId();?>.banner-background{background: url('<?php echo $image;?>') no-repeat center center transparent;background-size: cover;}
		@media (max-width: 650px) {#banner-image-<?php echo $banner->getId();?>.banner-background{background: url('<?php echo $respImage;?>') no-repeat center center transparent; background-size: cover;}}</style>
<?php } ?>