<?php 
$banner = $this->getBanner(); 
$color = ($banner->getFontColor() != '') ? $banner->getFontColor() : '#ffffff';
?>
<section id="banner-video-<?php echo $banner->getId();?>" class="frame <?php echo $banner->getBannerClass();?> banner-background">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-12">
				<div class="video-container">
					<iframe src="https://www.youtube.com/embed/<?php echo $banner->getClickUrl()?>?modestbranding=0&amp;showinfo=0&amp;controls=1&amp;rel=0" allowfullscreen="" frameborder="0"></iframe>
				</div>
			</div>
		</div>
	</div>
</section>
<?php if($banner->getBannerCss()){ ?><style><?php echo $this->cleanCss($banner->getBannerCss()) ?></style><?php } ?>
<?php if($banner->getImage()){ ?>
	<?php 
		$image = $this->getBannerImageUrl($banner); // imagen desktop
		$respImage = ($banner->getImageresp()) ? $this->getBannerImageUrl($banner, 'responsive') : $image; //imagen mobile
	?>
	<style>
		#banner-video-<?php echo $banner->getId();?>.banner-background{
			background: url('<?php echo $image;?>') no-repeat center center transparent; 
			background-size: cover;
		}
		@media (max-width: 650px) {
			#banner-video-<?php echo $banner->getId();?>.banner-background{
				background: url('<?php echo $respImage;?>') no-repeat center center transparent; 
				background-size: cover;
			}
		}
	</style>
<?php } ?>