<?php 
$banner = $this->getBanner(); 
$color = ($banner->getFontColor() != '') ? $banner->getFontColor() : '#ffffff';
?>
<section 
	id="banner-video-<?php echo $banner->getId();?>" 
	class="frame <?php echo $banner->getBannerClass();?>"
	<?php if($banner->getImage()){ ?>
		style="background: url('<?php echo $this->getBannerImageUrl($banner);?>') no-repeat center center transparent; background-size: cover;"
	<?php } ?>
>
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-12">
				<div class="video-container">
					<iframe src="https://www.youtube.com/embed/<?php echo $banner->getClickUrl()?>?modestbranding=0&amp;showinfo=0&amp;controls=1&amp;rel=0" allowfullscreen="" frameborder="0"></iframe>
				</div>
			</div>
		</div>
	</div>
</section>