<ul class="cms-menu">
	<li class="parent">
		<strong>Support</strong><ul>
			<li><a href="https://www.jamaudio.com/customer-support/shipping-and-delivery"><span>Shipping &amp; Delivery</span></a></li>
			<li><a href="https://www.jamaudio.com/customer-support/returns"><span>Returns</span></a></li>
			<li><a href="https://www.jamaudio.com/customer-support/instruction-books"><span>Instruction Books</span></a></li>
			<li><a href="https://www.jamaudio.com/customer-support/wifi-help"><span>WIFI Help Page</span></a></li>
			<li><a href="https://www.jamaudio.com/customer-support/product-registration"><span>Product Registration</span></a></li>
			<li><a href="https://www.jamaudio.com/customer-support/warranty-1yr"><span>One Year Limited Warranty</span></a></li>
			<li><a href="https://www.jamaudio.com/customer-support/where-to-buy"><span>Where to Buy</span></a></li>
			<li><a href="https://www.jamaudio.com/customer-support/contact-us"><span>Contact Us</span></a></li>
		</ul>
	</li>
</ul>