<div class="block">
    <div class="block-title">
        <strong><?php echo $this->getTitle() ?></strong>
    </div>
    
    <?php if($this->getOrderStatus() == 'canceled'){ ?>
        <div class="box-content">
            <div class="canceled-progress-bar">
                <div class="processed">
                    <?php echo __('Confirmed order') ?>
                </div>
                <div class="processed">
                    <?php echo __('Order canceled') ?>
                </div>
            </div>
        </div>
    <?php } else {?>
        <div class="box-content">
            <div class="normal-progress-bar">
                <div class="processed">
                    <?php echo __('Confirmed order') ?>
                </div>
                <div class="<?php echo ($this->getOrderStatus() == 'processing' ? 'processed' : 'no-processed') ?>">
                    <?php echo __('Payment Processed') ?>
                </div>
            </div>
            <div class="box-actions">
                <?php echo __('Guide generated') ?>
                <?php if($this->getOrderGuide() == 1){ ?>
                    
                        <?php if($this->getMienvioDataStatus()){ ?>
                            
                                <span><?php echo __('Tracking number') ?>: <?php echo $this->getMienvioData()->tracking_number ?></span>
                                <a class="action" href="<?php echo $this->getMienvioData()->tracking_url ?>" target="_blank"><li><?php echo __('Tracking url') ?></li></a>
                                <a class="action" href="<?php echo $this->getMienvioData()->label_url ?>" target="_blank"><li><?php echo __('PDF Information') ?></li></a>
                            
                        <?php } else{ ?>
                            <span><?php echo __('Tracking information is not available. Try again later') ?></span>
                        <?php } ?>
                    
                <?php } ?>
            </div>
                <div class="<?php echo ($this->getOrderGuide() == 1 ? 'processed' : 'no-processed') ?>">
                    <?php echo __('Guide generated') ?>
                    <?php if($this->getOrderGuide() == 1){ ?>
                        <div class="guide-generated">
                            <?php if($this->getMienvioDataStatus()){ ?>
                                <ul class="tracking-detail">
                                    <li><?php echo __('Tracking number') ?>: <?php echo $this->getMienvioData()->tracking_number ?></li>
                                    <a class="action" href="<?php echo $this->getMienvioData()->tracking_url ?>" target="_blank"><li><?php echo __('Tracking url') ?></li></a>
                                    <a class="action" href="<?php echo $this->getMienvioData()->label_url ?>" target="_blank"><li><?php echo __('PDF Information') ?></li></a>
                                </ul>
                            <?php } else{ ?>
                                <span><?php echo __('Tracking information is not available. Try again later') ?></span>
                            <?php } ?>
                        </div>
                    <?php } ?>
                </div>
                <div class="<?php echo ($this->getOrderDelivery() == 1 ? 'processed' : 'no-processed') ?>">
                    <?php echo __('Order delivered') ?>
                </div>
            
        </div>
    <?php } ?>
</div>
