<div class="container">
    <div class="row">
        <h1 class="page-title"><?php echo $this->getTitle() ?></h1>
        <div class="order-progress-bar">            
            <?php if($this->getOrderStatus() == 'canceled'){ ?>
                <div class="canceled-progress-bar">
                    <div class="processed">
                        <?php echo __('Confirmed order') ?>
                    </div>
                    <div class="processed">
                        <?php echo __('Order canceled') ?>
                    </div>
                </div>
            <?php } else {?>
                <div class="normal-progress-bar">
                    <div class="processed">
                        <?php echo __('Confirmed order') ?>
                    </div>
                    <div class="<?php echo ($this->getOrderStatus() == 'processing' ? 'processed' : 'no-processed') ?>">
                        <?php echo __('Payment Processed') ?>
                    </div>
                    <div class="<?php echo ($this->getOrderGuide() == 1 ? 'processed' : 'no-processed') ?>">
                        <?php echo __('Guide generated') ?>
                        <?php if($this->getOrderGuide() == 1){ ?>
                            <div class="guide-generated">
                                <?php if($this->getMienvioDataStatus()){ ?>
                                    <ul class="tracking-detail">
                                        <li><?php echo __('Tracking number') ?>: <?php echo $this->getMienvioData()->tracking_number ?></li>
                                        <li><?php echo __('Tracking url') ?>: <?php echo $this->getMienvioData()->tracking_url ?></li>
                                        <li><?php echo __('PDF Information') ?>: <?php echo $this->getMienvioData()->label_url ?></li>
                                    </ul>
                                    <?php print_r($this->getMienvioData()) ?>
                                <?php } else{ ?>
                                    <span><?php echo __('Tracking information is not available. Try again later') ?></span>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>
                    <div class="<?php echo ($this->getOrderDelivery() == 1 ? 'processed' : 'no-processed') ?>">
                        <?php echo __('Order delivered') ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
