<div class="block">
    <div class="block-title">
        <strong><?php echo $this->getTitle() ?></strong>
    </div>
    
    <?php if($this->getOrderStatus() == 'canceled'){ ?>
        <div class="block-content">
            <div class="canceled-progress-bar">
                <div class="processed">
                    <?php echo __('Confirmed order') ?>
                </div>
                <div class="processed">
                    <?php echo __('Order canceled') ?>
                </div>
            </div>
        </div>
    <?php } else {?>
        <div class="block-content">
            <div class="normal-progress-bar">
                <div class="processed">
                    <?php echo __('Confirmed order') ?>
                </div>
                <div class="<?php echo ($this->getOrderStatus() == 'processing' ? 'processed' : 'no-processed') ?>">
                    <?php echo __('Payment Processed') ?>
                </div>
            </div>
            
            <div class="<?php echo ($this->getOrderGuide() == 1 ? 'processed' : 'no-processed') ?>">
                <strong class="box-title"><?php echo __('Guide generated') ?></strong>
                <?php if($this->getOrderGuide() == 1){ ?>
                    <div class="guide-generated">
                        <?php if($this->getMienvioDataStatus()){ ?>
                            <ul class="tracking-detail">
                                <span><?php echo __('Tracking number') ?>: <?php echo $this->getMienvioData()->tracking_number ?></span>
                                <li><a class="action" href="<?php echo $this->getMienvioData()->tracking_url ?>" target="_blank"><?php echo __('Tracking url') ?></a></li>
                                <li><a class="action" href="<?php echo $this->getMienvioData()->label_url ?>" target="_blank"><?php echo __('PDF Information') ?></a></li>
                            </ul>
                        <?php } else{ ?>
                            <span><?php echo __('Tracking information is not available. Try again later') ?></span>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
            <div class="<?php echo ($this->getOrderDelivery() == 1 ? 'processed' : 'no-processed') ?>">
                <?php echo __('Order delivered') ?>
            </div>
        </div>
    <?php } ?>
</div>
