<?php

/**
 * @var $block \MagicToolbox\MagicZoomPlus\Block\Product\View\Gallery
 */
$_helperCdi = $this->helper('Cdi\Custom\Helper\Data');
$_product = $block->getProduct();
$discount = $_helperCdi->getDiscount($_product);

$helperGallery = $this->helper('Intcomex\GridImages\Helper\Data');
$type = $helperGallery->getViewGallery();
$_gallery_options = array (
    'allowfullscreen' => true,
    'arrows' => true,
    'height' => 700,
    'keyboard' => true,
    'loop' => true,
    'nav' => 'thumbs',
    'navarrows' => true,
    'navdir' => 'horizontal',
    'navtype' => 'slides',
    'showCaption' => false,
    'thumbheight' => 90,
    'thumbwidth' => 90,
    'transition' => 'slide',
    'transitionduration' => 500,
    'width' => 700,
);

$_gallery_options_fullscreen = array(
    "arrows" => false, 
   "loop" => true, 
   "nav" => "thumbs", 
   "navarrows" => false, 
   "navdir" => "horizontal", 
   "navtype" => "slides", 
   "showCaption" => false, 
   "transition" => "dissolve", 
   "transitionduration" => 500 
);
?>

<?php if ($discount != 0): 
    $discount = 100 - $discount; ?>
    <span class="product-tag disccount-tag">-<?php echo $discount ?>%</span>
<?php endif; ?>
<?php if ($_helperCdi->isNew($_product)): ?>
    <span class="product-tag new-tag"><?php /* @escapeNotVerified */ echo __('New') ?></span>
<?php endif; ?>
<?php if ($_product->getTypeId() == 'virtual'): ?>
    <span class="product-tag download-tag"></span>
<?php endif; ?>
<?php if ($_helperCdi->checkBestseller($_product)): ?>
    <span class="product-tag bestseller-tag"></span>
<?php endif;

$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage;
?>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
<img
    alt="main product photo"
    class="gallery-placeholder__image"
    src="<?= /* @noEscape */ $mainImageData['url'] ?>"
/>
</div>

<script type="text/x-magento-init">
{
    "[data-gallery-role=gallery-placeholder]": {
        "mage/gallery/gallery": {
            "mixins":["magnifier/magnify"],
            "magnifierOpts": <?= /* @escapeNotVerified */ $block->getMagnifier() ?>,
            "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
            "options": <?= /* @noEscape */ json_encode($_gallery_options) ?>,
            "fullscreen": <?= /* @noEscape */ json_encode($_gallery_options_fullscreen) ?>,
            "breakpoints": <?= /* @escapeNotVerified */ $block->getBreakpoints() ?>
        }
    }
}
</script>

