<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>

<section class="category-list">
    <div class="container">
        <div class="row">
        <?php  echo $block->getProductListHtml() ?>
        </div>
    </div>
</section>
