<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
  <section class="box-additional">
    <div class="container">
      <div class="row">
        <div class="product-tabs">
          <div class="tab-card">
            <?php $layout = $block->getLayout(); ?>
            <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
              <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                  $html = $layout->renderElement($name);
                  if (!trim($html)) {
                    continue;
                  }
                  $alias = $layout->getElementAlias($name);
                  $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                  <a class="data switch"
                     tabindex="-1"
                     data-toggle="switch"
                     href="#<?= /* @escapeNotVerified */ $alias ?>"
                     id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                      <?= /* @escapeNotVerified */ $label ?>
                  </a>
                </div>
                <div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                  <?= /* @escapeNotVerified */ $html ?>
                </div>
              <?php endforeach;?>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<?php endif; ?>
